/* SUDOMI 0.3.5 (V2, Fase 4.4) — traducciones de los textos nuevos de la V2 (barra de abajo, lista del arcade, reto del día,
 * nivel de la máquina, logros del arcade, y lo principal de Batalla naval, Duelo Mahjong y STOP clásico).
 * Funciona igual que js/lang-en.js y compañía: la clave es el texto en español ({} = un trozo que cambia) y js/i18n.js traduce en pantalla.
 * Para traducir un texto nuevo basta con añadirlo aquí en los cuatro idiomas. */
(function(){
 var K=[
  ['Arcade','Arcade','Arcade','Arcade','街机'],
  ['Más de SUDOMI','More from SUDOMI','Plus de SUDOMI','Mais do SUDOMI','更多 SUDOMI'],
  ['Sin perfil','No profile','Sans profil','Sem perfil','没有资料'],
  ['👤 Crear mi perfil','👤 Create my profile','👤 Créer mon profil','👤 Criar meu perfil','👤 创建我的资料'],
  ['Continuar','Continue','Continuer','Continuar','继续'],
  ['Fiesta','Party','Fête','Festa','派对'],
  ['Tablero','Board','Plateau','Tabuleiro','棋盘'],
  ['Cartas','Cards','Cartes','Cartas','纸牌'],
  ['Rápidos','Quick','Rapides','Rápidos','快速'],
  ['1–8 jugadores','1–8 players','1–8 joueurs','1–8 jogadores','1–8 人'],['2–8 jugadores','2–8 players','2–8 joueurs','2–8 jogadores','2–8 人'],
  ['2–4 jugadores','2–4 players','2–4 joueurs','2–4 jogadores','2–4 人'],['2 jugadores','2 players','2 joueurs','2 jogadores','2 人'],
  ['1 jugador','1 player','1 joueur','1 jogador','1 人'],
  ['4 en parejas','4 in pairs','4 en équipes','4 em duplas','4 人两队'],
  ['Online','Online','En ligne','Online','在线'],
  ['Nivel de la máquina','Computer level','Niveau de l’ordinateur','Nível do computador','电脑难度'],
  ['Normal','Normal','Normal','Normal','普通'],
  ['Reto de hoy: gana en {}','Today’s challenge: win at {}','Défi du jour : gagne à {}','Desafio de hoje: vença em {}','今日挑战：赢一局 {}'],
  ['Reto de hoy cumplido','Today’s challenge done','Défi du jour réussi','Desafio de hoje cumprido','今日挑战已完成'],
  ['Vuelve mañana por otro juego','Come back tomorrow for another game','Reviens demain pour un autre jeu','Volte amanhã para outro jogo','明天再来挑战别的游戏'],
  ['Vuelve mañana por otro juego · racha de {} día','Come back tomorrow for another game · {}-day streak','Reviens demain pour un autre jeu · série de {} jour','Volte amanhã para outro jogo · sequência de {} dia','明天再来 · 连续 {} 天'],
  ['Vuelve mañana por otro juego · racha de {} días','Come back tomorrow for another game · {}-day streak','Reviens demain pour un autre jeu · série de {} jours','Volte amanhã para outro jogo · sequência de {} dias','明天再来 · 连续 {} 天'],
  ['+40 XP · racha de {} día','+40 XP · {}-day streak','+40 XP · série de {} jour','+40 XP · sequência de {} dia','+40 XP · 连续 {} 天'],
  ['+40 XP · racha de {} días','+40 XP · {}-day streak','+40 XP · série de {} jours','+40 XP · sequência de {} dias','+40 XP · 连续 {} 天'],
  ['🎯 ¡Reto del día cumplido!','🎯 Daily challenge done!','🎯 Défi du jour réussi !','🎯 Desafio do dia cumprido!','🎯 今日挑战完成！'],
  ['Carrera de parejas: cada quien con su tablero.','A race for pairs: each player has their own board.','Course aux paires : chacun son plateau.','Corrida de pares: cada um com seu tabuleiro.','配对竞速：每人一张牌桌。'],
  ['📝 Modo clásico','📝 Classic mode','📝 Mode classique','📝 Modo clássico','📝 经典模式'],
  ['La hoja de siempre: 6 columnas, 5 rondas y piedra, papel o tijera para poner la letra.','The paper sheet: 6 columns, 5 rounds, and rock-paper-scissors to pick the letter.','La feuille de toujours : 6 colonnes, 5 manches et pierre-feuille-ciseaux pour choisir la lettre.','A folha de sempre: 6 colunas, 5 rodadas e pedra, papel ou tesoura para escolher a letra.','经典纸张：6 列、5 轮，用石头剪刀布决定谁选字母。'],
  ['Jugador de arcade','Arcade player','Joueur d’arcade','Jogador de arcade','街机玩家'],
  ['Termina 10 partidas en el arcade','Finish 10 arcade games','Termine 10 parties d’arcade','Termine 10 partidas no arcade','完成 10 局街机游戏'],
  ['Mano caliente','Hot hand','Main chaude','Mão quente','手感火热'],
  ['Gana 10 partidas en el arcade','Win 10 arcade games','Gagne 10 parties d’arcade','Vença 10 partidas no arcade','赢得 10 局街机游戏'],
  ['Gana una partida de DOS','Win a game of DOS','Gagne une partie de DOS','Vença uma partida de DOS','赢一局 DOS'],
  ['Rey del STOP','King of STOP','Roi du STOP','Rei do STOP','STOP 之王'],
  ['Gana una ronda de STOP o una partida de STOP clásico','Win a STOP round or a classic STOP game','Gagne une manche de STOP ou une partie de STOP classique','Vença uma rodada de STOP ou uma partida de STOP clássico','赢一轮 STOP 或一局经典 STOP'],
  ['Corona de Parchimi','Parchimi crown','Couronne de Parchimi','Coroa de Parchimi','Parchimi 王冠'],
  ['Gana una partida de Parchimi','Win a game of Parchimi','Gagne une partie de Parchimi','Vença uma partida de Parchimi','赢一局 Parchimi'],
  ['Almirante','Admiral','Amiral','Almirante','海军上将'],
  ['Gana una Batalla naval','Win a Sea Battle','Gagne une Bataille navale','Vença uma Batalha naval','赢一局海战'],
  ['Ojo de águila','Eagle eye','Œil de lynx','Olho de águia','鹰眼'],
  ['Gana un Duelo Mahjong','Win a Mahjong Duel','Gagne un Duel de Mahjong','Vença um Duelo de Mahjong','赢一局麻将对决'],
  ['▶ Jugar','▶ Play','▶ Jouer','▶ Jogar','▶ 开始'],
  ['🌐 Crear sala','🌐 Create room','🌐 Créer un salon','🌐 Criar sala','🌐 创建房间'],
  ['↻ Jugar otra vez','↻ Play again','↻ Rejouer','↻ Jogar de novo','↻ 再来一局'],
  ['Modo de juego','Game mode','Mode de jeu','Modo de jogo','游戏模式'],
  ['Clásico','Classic','Classique','Clássico','经典'],
  ['Táctico','Tactical','Tactique','Tático','战术'],
  ['Coloca tu flota','Place your fleet','Place ta flotte','Posicione sua frota','布置你的舰队'],
  ['🎲 Al azar','🎲 Random','🎲 Au hasard','🎲 Aleatório','🎲 随机'],
  ['✅ Listo','✅ Ready','✅ Prêt','✅ Pronto','✅ 准备好了'],
  ['Arrastra cada barco a donde lo quieras. El botón ↻ de su esquina lo pone de pie o acostado.','Drag each ship where you want it. The ↻ button on its corner turns it upright or flat.','Fais glisser chaque navire où tu veux. Le bouton ↻ dans son coin le met debout ou couché.','Arraste cada navio para onde quiser. O botão ↻ no canto o coloca de pé ou deitado.','把每艘船拖到想放的位置。船角上的 ↻ 按钮可以让它竖放或横放。'],
  ['🎯 Mar rival','🎯 Enemy sea','🎯 Mer ennemie','🎯 Mar inimigo','🎯 敌方海域'],
  ['🚢 Mi flota','🚢 My fleet','🚢 Ma flotte','🚢 Minha frota','🚢 我的舰队'],
  ['🎯 Elige 3 casillas y fija tu ataque','🎯 Pick 3 cells and lock your attack','🎯 Choisis 3 cases et verrouille ton attaque','🎯 Escolha 3 casas e trave seu ataque','🎯 选择 3 格并锁定攻击'],
  ['🔒 Fijar ataque','🔒 Lock attack','🔒 Verrouiller l’attaque','🔒 Travar ataque','🔒 锁定攻击'],
  ['🔒 Ataque fijado. Esperando a {}…','🔒 Attack locked. Waiting for {}…','🔒 Attaque verrouillée. En attente de {}…','🔒 Ataque travado. Esperando {}…','🔒 攻击已锁定。等待 {}…'],
  ['⚠️ {} está atacando tu flota','⚠️ {} is attacking your fleet','⚠️ {} attaque ta flotte','⚠️ {} está atacando sua frota','⚠️ {} 正在攻击你的舰队'],
  ['¡Fuego!','Fire!','Feu !','Fogo!','开火！'],
  ['🏆 ¡Ganaste la batalla!','🏆 You won the battle!','🏆 Tu as gagné la bataille !','🏆 Você venceu a batalha!','🏆 你赢得了战斗！'],
  ['💀 Ganó {}','💀 {} won','💀 {} a gagné','💀 {} venceu','💀 {} 赢了'],
  ['🤝 ¡Empate!','🤝 Draw!','🤝 Égalité !','🤝 Empate!','🤝 平局！'],
  ['Prepárate…','Get ready…','Prépare-toi…','Prepare-se…','准备…'],
  ['🀄 ¡Busca las parejas!','🀄 Find the pairs!','🀄 Trouve les paires !','🀄 Encontre os pares!','🀄 找出配对！'],
  ['✅ ¡Pareja!','✅ Pair!','✅ Paire !','✅ Par!','✅ 配对成功！'],
  ['👀 Ojo: ahora se parecen mucho','👀 Careful: they look alike now','👀 Attention : elles se ressemblent beaucoup','👀 Atenção: agora são muito parecidas','👀 注意：现在的牌很相似'],
  ['🀄 Sigue buscando','🀄 Keep looking','🀄 Continue à chercher','🀄 Continue procurando','🀄 继续找'],
  ['Te equivocaste','Wrong pair','Mauvaise paire','Par errado','配错了'],
  ['⛔ No son iguales: bloqueado 2 segundos','⛔ Not a match: locked for 2 seconds','⛔ Pas pareilles : bloqué 2 secondes','⛔ Não são iguais: bloqueado por 2 segundos','⛔ 不一样：锁定 2 秒'],
  ['Esa ficha está bloqueada: necesita un lado libre y nada encima','That tile is blocked: it needs a free side and nothing on top','Cette tuile est bloquée : il faut un côté libre et rien dessus','Essa peça está bloqueada: precisa de um lado livre e nada em cima','这张牌被挡住了：需要一侧空着且上面没有牌'],
  ['🏆 ¡Ganaste! Terminaste en {}','🏆 You won! Finished in {}','🏆 Gagné ! Terminé en {}','🏆 Você venceu! Terminou em {}','🏆 你赢了！用时 {}'],
  ['De muy distintas a muy parecidas','From very different to very alike','De très différentes à très semblables','De muito diferentes a muito parecidas','从很不一样到非常相似'],
  ['STOP clásico','Classic STOP','STOP classique','STOP clássico','经典 STOP'],
  ['✊ ✋ ✌️ ¿Quién pone la primera letra?','✊ ✋ ✌️ Who picks the first letter?','✊ ✋ ✌️ Qui choisit la première lettre ?','✊ ✋ ✌️ Quem escolhe a primeira letra?','✊ ✋ ✌️ 谁来选第一个字母？'],
  ['Elige. Quien gane pone la primera letra.','Choose. The winner picks the first letter.','Choisis. Le gagnant choisit la première lettre.','Escolha. Quem ganhar escolhe a primeira letra.','出拳吧。赢的人选第一个字母。'],
  ['Piedra','Rock','Pierre','Pedra','石头'],['Papel','Paper','Feuille','Papel','布'],['Tijera','Scissors','Ciseaux','Tesoura','剪刀'],
  ['¡Empate! Otra vez…','Tie! Again…','Égalité ! Encore…','Empate! De novo…','平手！再来…'],
  ['🎲 Los dados deciden el orden','🎲 The dice decide the order','🎲 Les dés décident de l’ordre','🎲 Os dados decidem a ordem','🎲 掷骰子决定顺序'],
  ['🎲 Tirar el dado','🎲 Roll the die','🎲 Lancer le dé','🎲 Jogar o dado','🎲 掷骰子'],
  ['🔤 Te toca poner la letra','🔤 Your turn to pick the letter','🔤 À toi de choisir la lettre','🔤 Sua vez de escolher a letra','🔤 轮到你选字母'],
  ['Las letras tachadas ya salieron en esta sesión.','Crossed-out letters were already used this session.','Les lettres barrées sont déjà sorties dans cette session.','As letras riscadas já saíram nesta sessão.','划掉的字母本次已经用过。'],
  ['▶ Sí, iniciar','▶ Yes, start','▶ Oui, commencer','▶ Sim, começar','▶ 是的，开始'],
  ['Cambiar','Change','Changer','Trocar','更换'],
  ['¡START!','START!','START !','START!','开始！'],
  ['¡STOP!!!','STOP!!!','STOP !!!','STOP!!!','停！！！'],
  ['Letra','Letter','Lettre','Letra','字母'],['Nombre','Name','Prénom','Nome','名字'],['Animal','Animal','Animal','Animal','动物'],
  ['Fruta o verdura','Fruit or vegetable','Fruit ou légume','Fruta ou verdura','水果或蔬菜'],['Ciudad o país','City or country','Ville ou pays','Cidade ou país','城市或国家'],
  ['Cosa','Thing','Chose','Coisa','物品'],['Comida','Food','Plat','Comida','食物'],['Total','Total','Total','Total','总分'],
  ['Siguiente ronda','Next round','Manche suivante','Próxima rodada','下一轮'],
  ['Ver resultado final','See final result','Voir le résultat final','Ver resultado final','查看最终结果'],
  ['↻ Jugar otra partida','↻ Play another game','↻ Rejouer une partie','↻ Jogar outra partida','↻ 再玩一局'],
  ['↻ Revancha','↻ Rematch','↻ Revanche','↻ Revanche','↻ 再战'],['📤 Compartir','📤 Share','📤 Partager','📤 Compartilhar','📤 分享'],
  ['Ver el tablero','See the board','Voir le plateau','Ver o tabuleiro','查看棋盘'],['Todos los juegos','All games','Tous les jeux','Todos os jogos','所有游戏'],
  ['¡Ganaste la batalla!','You won the battle!','Tu as gagné la bataille !','Você venceu a batalha!','你赢得了战斗！'],['¡Ganaste la carrera!','You won the race!','Tu as gagné la course !','Você venceu a corrida!','你赢得了比赛！'],
  ['¡Ganaste la partida!','You won the game!','Tu as gagné la partie !','Você venceu a partida!','你赢了这一局！'],['Ganó {}','{} won','{} a gagné','{} venceu','{} 赢了'],
  ['✨ Auto','✨ Auto','✨ Auto','✨ Auto','✨ 自动'],
  ['Contra la máquina','Against the computer','Contre l’ordinateur','Contra o computador','对战电脑'],['En este dispositivo','On this device','Sur cet appareil','Neste aparelho','在本设备上'],
  ['Los barcos no pueden tocarse','Ships can’t touch','Les navires ne peuvent pas se toucher','Os navios não podem se tocar','舰船不能相邻'],
  ['📅 Tablero del día','📅 Daily board','📅 Grille du jour','📅 Tabuleiro do dia','📅 每日棋盘'],['El mismo tablero para todos · nivel Medio','The same board for everyone · Medium level','La même grille pour tous · niveau Moyen','O mesmo tabuleiro para todos · nível Médio','所有人同一张棋盘 · 中等难度'],
  ['Hecho hoy en {} · mejora tu tiempo','Done today in {} · beat your time','Fait aujourd’hui en {} · améliore ton temps','Feito hoje em {} · melhore seu tempo','今天用时 {} · 再创佳绩'],
  ['♛ Coronar: Dama','♛ Promote: Queen','♛ Promotion : Dame','♛ Promover: Dama','♛ 升变：后'],['♜ Coronar: Torre','♜ Promote: Rook','♜ Promotion : Tour','♜ Promover: Torre','♜ 升变：车'],
  ['♝ Coronar: Alfil','♝ Promote: Bishop','♝ Promotion : Fou','♝ Promover: Bispo','♝ 升变：象'],['♞ Coronar: Caballo','♞ Promote: Knight','♞ Promotion : Cavalier','♞ Promover: Cavalo','♞ 升变：马'],
  ['¡Nuevo récord!','New record!','Nouveau record !','Novo recorde!','新纪录！'],['¡Tablero despejado!','Board cleared!','Plateau terminé !','Tabuleiro limpo!','清空牌桌！'],['Tu récord','Your record','Ton record','Seu recorde','你的纪录'],
  ['Fácil','Easy','Facile','Fácil','简单'],['Difícil','Hard','Difficile','Difícil','困难'],
  ['Tus fichas','Your chips','Tes jetons','Suas fichas','你的筹码'],['Haz tu apuesta','Place your bet','Fais ta mise','Faça sua aposta','请下注'],
  ['Quitar','Clear','Effacer','Limpar','清除'],['Repartiendo…','Dealing…','Distribution…','Distribuindo…','发牌中…'],['Tu turno','Your turn','À toi','Sua vez','轮到你'],
  ['Pedir','Hit','Tirer','Pedir','要牌'],['Plantarse','Stand','Rester','Parar','停牌'],['Doblar','Double','Doubler','Dobrar','加倍'],['Dividir','Split','Séparer','Dividir','分牌'],
  ['Otra mano','Another hand','Encore une main','Outra mão','再来一手'],['Juega la banca…','Dealer plays…','La banque joue…','A banca joga…','庄家行动…'],
  ['Banca','Dealer','Banque','Banca','庄家'],['Tú','You','Toi','Você','你'],['Ganas','You win','Gagné','Você ganha','你赢了'],['¡Blackjack!','Blackjack!','Blackjack !','Blackjack!','黑杰克！'],
  ['Pierdes','You lose','Perdu','Você perde','你输了'],['Te pasaste','Bust','Sauté','Estourou','爆牌'],
  ['Empate: recuperas tu apuesta','Push: you get your bet back','Égalité : tu récupères ta mise','Empate: você recupera a aposta','平局：退回下注'],
  ['🏆 Ganas {} fichas','🏆 You win {} chips','🏆 Tu gagnes {} jetons','🏆 Você ganha {} fichas','🏆 你赢得 {} 筹码'],['Pierdes {} fichas','You lose {} chips','Tu perds {} jetons','Você perde {} fichas','你输掉 {} 筹码'],
  ['Te quedaste sin fichas.','You are out of chips.','Tu n’as plus de jetons.','Você ficou sem fichas.','你的筹码用完了。'],['No tienes fichas suficientes.','You don’t have enough chips.','Tu n’as pas assez de jetons.','Você não tem fichas suficientes.','筹码不足。'],
  ['Retirarse','Fold','Se coucher','Desistir','弃牌'],['Igualar {}','Call {}','Suivre {}','Pagar {}','跟注 {}'],['Subir a','Raise to','Relancer à','Aumentar para','加注到'],
  ['Siguiente mano','Next hand','Main suivante','Próxima mão','下一手'],['▶ Repartir','▶ Deal','▶ Distribuer','▶ Distribuir','▶ 发牌'],['Bote','Pot','Pot','Pote','底池'],
  ['Se retira','Folds','Se couche','Desiste','弃牌'],['Te retiraste','You folded','Tu t’es couché','Você desistiu','你已弃牌'],
  ['Carta alta','High card','Carte haute','Carta alta','高牌'],['Pareja','Pair','Paire','Par','一对'],['Doble pareja','Two pair','Double paire','Dois pares','两对'],['Trío','Three of a kind','Brelan','Trinca','三条'],
  ['Escalera','Straight','Suite','Sequência','顺子'],['Full','Full house','Full','Full house','葫芦'],
  ['Escalera de color','Straight flush','Quinte flush','Straight flush','同花顺'],['Escalera real','Royal flush','Quinte flush royale','Royal flush','皇家同花顺'],
  ['Apuesta tus fichas, dobla, divide y gánale a la banca.','Bet your chips, double, split and beat the dealer.','Mise tes jetons, double, sépare et bats la banque.','Aposte suas fichas, dobre, divida e vença a banca.','下注、加倍、分牌，赢过庄家。'],
  ['Texas Hold’em con fichas: apuesta, sube o retírate.','Texas Hold’em with chips: bet, raise or fold.','Texas Hold’em avec jetons : mise, relance ou couche-toi.','Texas Hold’em com fichas: aposte, aumente ou desista.','带筹码的德州扑克：下注、加注或弃牌。'],
  ['Veintiuno','Twenty-one','Vingt-et-un','Vinte e um','二十一点'],['Gana una mano de Blackjack','Win a hand of Blackjack','Gagne une main de Blackjack','Vença uma mão de Blackjack','赢一手二十一点'],
  ['Cara de póker','Poker face','Poker face','Cara de pôquer','扑克脸'],['Gana un bote en el Póker','Win a pot at Poker','Gagne un pot au Poker','Vença um pote no Pôquer','在扑克中赢下一个底池'],
  ['Banca llena','Full bank','Banque pleine','Banca cheia','筹码满满'],['Junta 5,000 fichas de juego','Collect 5,000 play chips','Réunis 5 000 jetons','Junte 5.000 fichas','攒够 5,000 筹码'],
  ['Toca un número con sus banderas puestas para abrir de golpe sus vecinas.','Tap a number with its flags set to open its neighbours at once.','Touche un chiffre avec ses drapeaux posés pour ouvrir ses voisines d’un coup.','Toque um número com as bandeiras colocadas para abrir as vizinhas de uma vez.','点击已插好旗子的数字，可一次翻开周围的格子。']
 ];
 var L=['en','fr','pt','zh'];
 window.__sudomiLangQueue=window.__sudomiLangQueue||[];
 L.forEach(function(l,i){var D={};K.forEach(function(r){D[r[0]]=r[i+1]});if(window.SudomiI18n&&SudomiI18n.add)SudomiI18n.add(l,D);else window.__sudomiLangQueue.push([l,D])});
})();
