/* SUDOMI 0.3.5 (V2, Fase 4.4) — traducciones de los textos nuevos de la V2 (barra de abajo, lista del arcade, reto del día,
 * nivel de la máquina, logros del arcade, y lo principal de Batalla naval, Duelo Mahjong y STOP clásico).
 * Funciona igual que js/lang-en.js y compañía: la clave es el texto en español ({} = un trozo que cambia) y js/i18n.js traduce en pantalla.
 * Para traducir un texto nuevo basta con añadirlo aquí en los cuatro idiomas. */
(function(){
 var K=[
  ['Arcade','Arcade','Arcade','Arcade','街机'],
  ['Más de SUDOMI','More from SUDOMI','Plus de SUDOMI','Mais do SUDOMI','更多 SUDOMI'],
  ['Sin perfil','No profile','Sans profil','Sem perfil','没有资料'],
  ['👤 Crear mi perfil','👤 Create my profile','👤 Créer mon profil','👤 Criar meu perfil','👤 创建我的资料'],
  ['Continuar','Continue','Continuer','Continuar','继续'],
  ['Fiesta','Party','Fête','Festa','派对'],
  ['Tablero','Board','Plateau','Tabuleiro','棋盘'],
  ['Cartas','Cards','Cartes','Cartas','纸牌'],
  ['Rápidos','Quick','Rapides','Rápidos','快速'],
  ['1–8 jugadores','1–8 players','1–8 joueurs','1–8 jogadores','1–8 人'],['2–8 jugadores','2–8 players','2–8 joueurs','2–8 jogadores','2–8 人'],
  ['2–4 jugadores','2–4 players','2–4 joueurs','2–4 jogadores','2–4 人'],['2 jugadores','2 players','2 joueurs','2 jogadores','2 人'],
  ['1 jugador','1 player','1 joueur','1 jogador','1 人'],
  ['4 en parejas','4 in pairs','4 en équipes','4 em duplas','4 人两队'],
  ['Online','Online','En ligne','Online','在线'],
  ['Nivel de la máquina','Computer level','Niveau de l’ordinateur','Nível do computador','电脑难度'],
  ['Normal','Normal','Normal','Normal','普通'],
  ['Reto de hoy: gana en {}','Today’s challenge: win at {}','Défi du jour : gagne à {}','Desafio de hoje: vença em {}','今日挑战：赢一局 {}'],
  ['Reto de hoy cumplido','Today’s challenge done','Défi du jour réussi','Desafio de hoje cumprido','今日挑战已完成'],
  ['Vuelve mañana por otro juego','Come back tomorrow for another game','Reviens demain pour un autre jeu','Volte amanhã para outro jogo','明天再来挑战别的游戏'],
  ['Vuelve mañana por otro juego · racha de {} día','Come back tomorrow for another game · {}-day streak','Reviens demain pour un autre jeu · série de {} jour','Volte amanhã para outro jogo · sequência de {} dia','明天再来 · 连续 {} 天'],
  ['Vuelve mañana por otro juego · racha de {} días','Come back tomorrow for another game · {}-day streak','Reviens demain pour un autre jeu · série de {} jours','Volte amanhã para outro jogo · sequência de {} dias','明天再来 · 连续 {} 天'],
  ['+40 XP · racha de {} día','+40 XP · {}-day streak','+40 XP · série de {} jour','+40 XP · sequência de {} dia','+40 XP · 连续 {} 天'],
  ['+40 XP · racha de {} días','+40 XP · {}-day streak','+40 XP · série de {} jours','+40 XP · sequência de {} dias','+40 XP · 连续 {} 天'],
  ['🎯 ¡Reto del día cumplido!','🎯 Daily challenge done!','🎯 Défi du jour réussi !','🎯 Desafio do dia cumprido!','🎯 今日挑战完成！'],
  ['Carrera de parejas: cada quien con su tablero.','A race for pairs: each player has their own board.','Course aux paires : chacun son plateau.','Corrida de pares: cada um com seu tabuleiro.','配对竞速：每人一张牌桌。'],
  ['📝 Modo clásico','📝 Classic mode','📝 Mode classique','📝 Modo clássico','📝 经典模式'],
  ['La hoja de siempre: 6 columnas, 5 rondas y piedra, papel o tijera para poner la letra.','The paper sheet: 6 columns, 5 rounds, and rock-paper-scissors to pick the letter.','La feuille de toujours : 6 colonnes, 5 manches et pierre-feuille-ciseaux pour choisir la lettre.','A folha de sempre: 6 colunas, 5 rodadas e pedra, papel ou tesoura para escolher a letra.','经典纸张：6 列、5 轮，用石头剪刀布决定谁选字母。'],
  ['Jugador de arcade','Arcade player','Joueur d’arcade','Jogador de arcade','街机玩家'],
  ['Termina 10 partidas en el arcade','Finish 10 arcade games','Termine 10 parties d’arcade','Termine 10 partidas no arcade','完成 10 局街机游戏'],
  ['Mano caliente','Hot hand','Main chaude','Mão quente','手感火热'],
  ['Gana 10 partidas en el arcade','Win 10 arcade games','Gagne 10 parties d’arcade','Vença 10 partidas no arcade','赢得 10 局街机游戏'],
  ['Gana una partida de DOS','Win a game of DOS','Gagne une partie de DOS','Vença uma partida de DOS','赢一局 DOS'],
  ['Rey del STOP','King of STOP','Roi du STOP','Rei do STOP','STOP 之王'],
  ['Gana una ronda de STOP o una partida de STOP clásico','Win a STOP round or a classic STOP game','Gagne une manche de STOP ou une partie de STOP classique','Vença uma rodada de STOP ou uma partida de STOP clássico','赢一轮 STOP 或一局经典 STOP'],
  ['Corona de Parchimi','Parchimi crown','Couronne de Parchimi','Coroa de Parchimi','Parchimi 王冠'],
  ['Gana una partida de Parchimi','Win a game of Parchimi','Gagne une partie de Parchimi','Vença uma partida de Parchimi','赢一局 Parchimi'],
  ['Almirante','Admiral','Amiral','Almirante','海军上将'],
  ['Gana una Batalla naval','Win a Sea Battle','Gagne une Bataille navale','Vença uma Batalha naval','赢一局海战'],
  ['Ojo de águila','Eagle eye','Œil de lynx','Olho de águia','鹰眼'],
  ['Gana un Duelo Mahjong','Win a Mahjong Duel','Gagne un Duel de Mahjong','Vença um Duelo de Mahjong','赢一局麻将对决'],
  ['▶ Jugar','▶ Play','▶ Jouer','▶ Jogar','▶ 开始'],
  ['🌐 Crear sala','🌐 Create room','🌐 Créer un salon','🌐 Criar sala','🌐 创建房间'],
  ['↻ Jugar otra vez','↻ Play again','↻ Rejouer','↻ Jogar de novo','↻ 再来一局'],
  ['Modo de juego','Game mode','Mode de jeu','Modo de jogo','游戏模式'],
  ['Clásico','Classic','Classique','Clássico','经典'],
  ['Táctico','Tactical','Tactique','Tático','战术'],
  ['Coloca tu flota','Place your fleet','Place ta flotte','Posicione sua frota','布置你的舰队'],
  ['🎲 Al azar','🎲 Random','🎲 Au hasard','🎲 Aleatório','🎲 随机'],
  ['✅ Listo','✅ Ready','✅ Prêt','✅ Pronto','✅ 准备好了'],
  ['Arrastra cada barco a donde lo quieras. El botón ↻ de su esquina lo pone de pie o acostado.','Drag each ship where you want it. The ↻ button on its corner turns it upright or flat.','Fais glisser chaque navire où tu veux. Le bouton ↻ dans son coin le met debout ou couché.','Arraste cada navio para onde quiser. O botão ↻ no canto o coloca de pé ou deitado.','把每艘船拖到想放的位置。船角上的 ↻ 按钮可以让它竖放或横放。'],
  ['🎯 Mar rival','🎯 Enemy sea','🎯 Mer ennemie','🎯 Mar inimigo','🎯 敌方海域'],
  ['🚢 Mi flota','🚢 My fleet','🚢 Ma flotte','🚢 Minha frota','🚢 我的舰队'],
  ['🎯 Elige 3 casillas y fija tu ataque','🎯 Pick 3 cells and lock your attack','🎯 Choisis 3 cases et verrouille ton attaque','🎯 Escolha 3 casas e trave seu ataque','🎯 选择 3 格并锁定攻击'],
  ['🔒 Fijar ataque','🔒 Lock attack','🔒 Verrouiller l’attaque','🔒 Travar ataque','🔒 锁定攻击'],
  ['🔒 Ataque fijado. Esperando a {}…','🔒 Attack locked. Waiting for {}…','🔒 Attaque verrouillée. En attente de {}…','🔒 Ataque travado. Esperando {}…','🔒 攻击已锁定。等待 {}…'],
  ['⚠️ {} está atacando tu flota','⚠️ {} is attacking your fleet','⚠️ {} attaque ta flotte','⚠️ {} está atacando sua frota','⚠️ {} 正在攻击你的舰队'],
  ['¡Fuego!','Fire!','Feu !','Fogo!','开火！'],
  ['🏆 ¡Ganaste la batalla!','🏆 You won the battle!','🏆 Tu as gagné la bataille !','🏆 Você venceu a batalha!','🏆 你赢得了战斗！'],
  ['💀 Ganó {}','💀 {} won','💀 {} a gagné','💀 {} venceu','💀 {} 赢了'],
  ['🤝 ¡Empate!','🤝 Draw!','🤝 Égalité !','🤝 Empate!','🤝 平局！'],
  ['Prepárate…','Get ready…','Prépare-toi…','Prepare-se…','准备…'],
  ['🀄 ¡Busca las parejas!','🀄 Find the pairs!','🀄 Trouve les paires !','🀄 Encontre os pares!','🀄 找出配对！'],
  ['✅ ¡Pareja!','✅ Pair!','✅ Paire !','✅ Par!','✅ 配对成功！'],
  ['👀 Ojo: ahora se parecen mucho','👀 Careful: they look alike now','👀 Attention : elles se ressemblent beaucoup','👀 Atenção: agora são muito parecidas','👀 注意：现在的牌很相似'],
  ['🀄 Sigue buscando','🀄 Keep looking','🀄 Continue à chercher','🀄 Continue procurando','🀄 继续找'],
  ['Te equivocaste','Wrong pair','Mauvaise paire','Par errado','配错了'],
  ['⛔ No son iguales: bloqueado 2 segundos','⛔ Not a match: locked for 2 seconds','⛔ Pas pareilles : bloqué 2 secondes','⛔ Não são iguais: bloqueado por 2 segundos','⛔ 不一样：锁定 2 秒'],
  ['Esa ficha está bloqueada: necesita un lado libre y nada encima','That tile is blocked: it needs a free side and nothing on top','Cette tuile est bloquée : il faut un côté libre et rien dessus','Essa peça está bloqueada: precisa de um lado livre e nada em cima','这张牌被挡住了：需要一侧空着且上面没有牌'],
  ['🏆 ¡Ganaste! Terminaste en {}','🏆 You won! Finished in {}','🏆 Gagné ! Terminé en {}','🏆 Você venceu! Terminou em {}','🏆 你赢了！用时 {}'],
  ['De muy distintas a muy parecidas','From very different to very alike','De très différentes à très semblables','De muito diferentes a muito parecidas','从很不一样到非常相似'],
  ['STOP clásico','Classic STOP','STOP classique','STOP clássico','经典 STOP'],
  ['✊ ✋ ✌️ ¿Quién pone la primera letra?','✊ ✋ ✌️ Who picks the first letter?','✊ ✋ ✌️ Qui choisit la première lettre ?','✊ ✋ ✌️ Quem escolhe a primeira letra?','✊ ✋ ✌️ 谁来选第一个字母？'],
  ['Elige. Quien gane pone la primera letra.','Choose. The winner picks the first letter.','Choisis. Le gagnant choisit la première lettre.','Escolha. Quem ganhar escolhe a primeira letra.','出拳吧。赢的人选第一个字母。'],
  ['Piedra','Rock','Pierre','Pedra','石头'],['Papel','Paper','Feuille','Papel','布'],['Tijera','Scissors','Ciseaux','Tesoura','剪刀'],
  ['¡Empate! Otra vez…','Tie! Again…','Égalité ! Encore…','Empate! De novo…','平手！再来…'],
  ['🎲 Los dados deciden el orden','🎲 The dice decide the order','🎲 Les dés décident de l’ordre','🎲 Os dados decidem a ordem','🎲 掷骰子决定顺序'],
  ['🎲 Tirar el dado','🎲 Roll the die','🎲 Lancer le dé','🎲 Jogar o dado','🎲 掷骰子'],
  ['🔤 Te toca poner la letra','🔤 Your turn to pick the letter','🔤 À toi de choisir la lettre','🔤 Sua vez de escolher a letra','🔤 轮到你选字母'],
  ['Las letras tachadas ya salieron en esta sesión.','Crossed-out letters were already used this session.','Les lettres barrées sont déjà sorties dans cette session.','As letras riscadas já saíram nesta sessão.','划掉的字母本次已经用过。'],
  ['▶ Sí, iniciar','▶ Yes, start','▶ Oui, commencer','▶ Sim, começar','▶ 是的，开始'],
  ['Cambiar','Change','Changer','Trocar','更换'],
  ['¡START!','START!','START !','START!','开始！'],
  ['¡STOP!!!','STOP!!!','STOP !!!','STOP!!!','停！！！'],
  ['Letra','Letter','Lettre','Letra','字母'],['Nombre','Name','Prénom','Nome','名字'],['Animal','Animal','Animal','Animal','动物'],
  ['Fruta o verdura','Fruit or vegetable','Fruit ou légume','Fruta ou verdura','水果或蔬菜'],['Ciudad o país','City or country','Ville ou pays','Cidade ou país','城市或国家'],
  ['Cosa','Thing','Chose','Coisa','物品'],['Comida','Food','Plat','Comida','食物'],['Total','Total','Total','Total','总分'],
  ['Siguiente ronda','Next round','Manche suivante','Próxima rodada','下一轮'],
  ['Ver resultado final','See final result','Voir le résultat final','Ver resultado final','查看最终结果'],
  ['↻ Jugar otra partida','↻ Play another game','↻ Rejouer une partie','↻ Jogar outra partida','↻ 再玩一局'],
  ['Toca un número con sus banderas puestas para abrir de golpe sus vecinas.','Tap a number with its flags set to open its neighbours at once.','Touche un chiffre avec ses drapeaux posés pour ouvrir ses voisines d’un coup.','Toque um número com as bandeiras colocadas para abrir as vizinhas de uma vez.','点击已插好旗子的数字，可一次翻开周围的格子。']
 ];
 var L=['en','fr','pt','zh'];
 window.__sudomiLangQueue=window.__sudomiLangQueue||[];
 L.forEach(function(l,i){var D={};K.forEach(function(r){D[r[0]]=r[i+1]});if(window.SudomiI18n&&SudomiI18n.add)SudomiI18n.add(l,D);else window.__sudomiLangQueue.push([l,D])});
})();
