/* Two-player Wi-Fi and pass-and-play arcade games. */
(()=>{
const names={domino:'Dominó',memory:'Memoria de animales',dotsboxes:'Puntos y cajas',stop:'STOP',mahjong:'Duelo Mahjong',blackjack:'Blackjack',poker:'Póker',escoba:'Escoba',rummy:'Rummy'};
const cats=['Nombre','Apellido','Animal','País','Ciudad','Comida','Fruta','Verdura','Color','Profesión','Deporte','Equipo deportivo','Artista o cantante','Canción','Película','Serie','Personaje ficticio','Marca','Objeto de la casa','Prenda de vestir','Parte del cuerpo','Transporte','Algo de la escuela','Algo de la playa','Algo que se lleva en una mochila','Algo que da miedo','Algo que se puede regalar','Algo dominicano'];
const pick=a=>a[Math.random()*a.length|0],shuffle=a=>a.sort(()=>Math.random()-.5),uid=()=>Math.random().toString(36).slice(2,8),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const stdDeck=()=>shuffle(['♠','♥','♦','♣'].flatMap(s=>Array.from({length:13},(_,i)=>({s,v:i+1,id:uid()}))));
const spanishDeck=()=>shuffle(['Oros','Copas','Espadas','Bastos'].flatMap(s=>[1,2,3,4,5,6,7,10,11,12].map(v=>({s,v,id:uid()}))));
function base(id,mode){return {id,mode,turn:0,over:false,winner:null,message:'Turno del Jugador 1.'}}
function create(id,mode='pvp'){
 let g=base(id,mode);
 if(id==='domino'){let d=shuffle(Array.from({length:7},(_,a)=>Array.from({length:7-a},(_,b)=>[a,a+b])).flat());g.hands=[d.slice(0,7),d.slice(7,14)];g.stock=d.slice(14);g.row=[];g.ends=[];g.passes=0;g.message='Coloca una ficha que coincida con un extremo.'}
 if(id==='memory'){let a=shuffle(Array.from({length:8},(_,i)=>['🐶','🐱','🦊','🐼','🐸','🦁','🐢','🦉'][i]).flatMap(x=>[x,x]));g.tiles=a.map((v,i)=>({v,id:i}));g.open=[];g.pairs=[0,0];g.locked=false}
 if(id==='dotsboxes'){g.w=4;g.edges={};g.boxes=Array(16).fill(-1);g.score=[0,0]}
 if(id==='stop'){g.letter=String.fromCharCode(65+(Math.random()*26|0));g.questions=shuffle([...cats]).slice(0,10);g.q=0;g.answers=[Array(10).fill(''),Array(10).fill('')];g.turn=0;g.left=20;g.votes=[Array(10).fill(null),Array(10).fill(null)];g.phase='answer';g.voteIndex=0;g.message=`Letra ${g.letter} · ${g.questions[0]} · tienes 20 segundos.`}
 if(id==='mahjong'){let t=['東','南','西','北','中','發','白','一萬','二萬','三萬','一筒','二筒'];g.tiles=shuffle(t.flatMap(v=>[0,1,2,3].map(()=>({v,id:uid()}))));g.selected=[];g.score=[0,0];g.turn=0;g.message='Elige dos fichas iguales del montón para ganar un punto.'}
 if(id==='blackjack'){g.deck=stdDeck();g.hands=[[],[]];g.dealer=[];g.stage='play';g.turn=0;g.hands[0].push(g.deck.pop(),g.deck.pop());g.hands[1].push(g.deck.pop(),g.deck.pop());g.dealer.push(g.deck.pop(),g.deck.pop());g.stood=[false,false]}
 if(id==='poker'){g.deck=stdDeck();g.hands=[[],[]];g.hands[0]=g.deck.splice(0,5);g.hands[1]=g.deck.splice(0,5);g.discard=[[],[]];g.stage='swap';g.turn=0;g.message='Elige hasta tres cartas para cambiar y confirma.'}
 if(id==='escoba'){g.deck=spanishDeck();g.hands=[g.deck.splice(0,3),g.deck.splice(0,3)];g.table=g.deck.splice(0,4);g.captured=[[],[]];g.last=-1;g.sel=[];g.score=[0,0]}
 if(id==='rummy'){g.deck=stdDeck();g.hands=[g.deck.splice(0,7),g.deck.splice(0,7)];g.discard=[g.deck.pop()];g.drawn=false;g.melds=[[],[]];g.message='Roba una carta; puedes bajar grupos de 3 o más y descartar.'}
 return g
}
function tile(c){return `<span class="extra-tile">${c.v===1?'A':c.v===11?'J':c.v===12?'Q':c.v===13?'K':c.v}${c.s}</span>`}
function domino(g){let h=g.hands[g.turn],valid=(t)=>!g.row.length||t.includes(g.ends[0])||t.includes(g.ends[1]);let html=`<div class="extra-status">${g.message}<br>Tu mano: ${h.length} · rival: ${g.hands[1-g.turn].length} · reserva: ${g.stock.length}</div><div class="domino-row">${g.row.map(t=>`<span class="extra-tile">${t[0]}|${t[1]}</span>`).join('')||'Mesa vacía'}</div><div class="extra-hand">${h.map((t,i)=>`<button data-a="play" data-i="${i}" ${!valid(t)||g.turn<0?'disabled':''}>${t[0]}|${t[1]}</button>`).join('')}</div><button data-a="draw" ${g.stock.length?'':'disabled'}>Robar ficha</button><button data-a="pass">Pasar turno</button>`;return html}
function memory(g){return `<div class="extra-status">Puntos: J1 ${g.pairs[0]} · J2 ${g.pairs[1]} ${g.locked?' · No hubo pareja. Pulsa continuar.':''}</div><div class="memory-grid">${g.tiles.map((t,i)=>`<button class="memory-card" data-a="tile" data-i="${i}" ${t.gone||g.open.includes(i)||g.open.length===2||g.locked?'disabled':''}>${t.gone||g.open.includes(i)?t.v:'?'}</button>`).join('')}</div>${g.locked?'<button data-a="continue">Ocultar y pasar turno</button>':''}`}
function dots(g){let n=g.w,html='<div class="dots-grid">';for(let y=0;y<=n;y++){for(let x=0;x<=n;x++){html+='<span class="dot"></span>';if(x<n){let k=`h${x},${y}`;html+=`<button class="dot-edge h ${g.edges[k]!==undefined?'on p'+g.edges[k]:''}" data-a="edge" data-k="${k}" ${g.edges[k]!==undefined?'disabled':''}></button>`}}if(y<n){for(let x=0;x<=n;x++){let k=`v${x},${y}`;html+=`<button class="dot-edge v ${g.edges[k]!==undefined?'on p'+g.edges[k]:''}" data-a="edge" data-k="${k}" ${g.edges[k]!==undefined?'disabled':''}></button>`;if(x<n)html+=`<span class="box-owner ${g.boxes[y*4+x]>=0?'p'+g.boxes[y*4+x]:''}"></span>`}}}return html+'</div><p class="extra-status">Cuadros: J1 '+g.score[0]+' · J2 '+g.score[1]+' — quien cierra un cuadro juega otra vez.</p>'}
function stop(g){if(g.phase==='answer')return `<p class="extra-status">Letra <b>${g.letter}</b> · Pregunta ${g.q+1}/10: <b>${esc(g.questions[g.q])}</b> · <span id="stopTimer">${g.left}</span>s · Jugador ${g.turn+1}</p><input id="stopAnswer" maxlength="40" placeholder="Tu respuesta"><button data-a="answer">Enviar</button>`;if(g.phase==='vote'){let i=g.voteIndex,p=1-g.turn;return `<p class="extra-status">Votación · Jugador ${g.turn+1}, evalúa la respuesta rival a <b>${esc(g.questions[i])}</b> con la letra ${g.letter}.</p><blockquote>${esc(g.answers[p][i]||'(vacía)')}</blockquote><button data-a="vote" data-v="1">Válida</button><button data-a="vote" data-v="0">No válida</button><p>Revisión ${i+1}/10</p>`}return `<h3>Fin de ronda · ${g.points[0]} a ${g.points[1]}</h3>${g.questions.map((q,i)=>`<p>${esc(q)}: ${esc(g.answers[0][i]||'—')} / ${esc(g.answers[1][i]||'—')}</p>`).join('')}<button data-a="again">Nueva ronda</button>`}
function mahjong(g){return `<p class="extra-status">Puntos: J1 ${g.score[0]} · J2 ${g.score[1]} · Elige dos fichas iguales.</p><div class="mahjong-grid">${g.tiles.map((t,i)=>`<button class="extra-tile ${g.selected.includes(i)?'selected':''}" data-a="tile" data-i="${i}" ${t.gone?'disabled':''}>${t.gone?'·':t.v}</button>`).join('')}</div>`}
function blackjack(g){let score=h=>h.reduce((s,c)=>s+(c.v>10?10:c.v===1?11:c.v),0);const hand=(h,hide)=>h.map((c,i)=>hide&&i===1?'🂠':tile(c)).join(' ');return `<p class="extra-status">${g.stage==='play'?`Turno Jugador ${g.turn+1}`:`Final · ${g.message}`}</p><p>Tu mano: ${hand(g.hands[g.turn],false)} · ${score(g.hands[g.turn])}</p><p>Rival: ${g.hands[1-g.turn].length} cartas · Banca: ${hand(g.dealer,g.stage==='play')}</p>${g.stage==='play'?'<button data-a="hit">Pedir</button><button data-a="stand">Plantarse</button>':''}`}
function poker(g){return `<p class="extra-status">${g.message} · Mano rival: ${g.hands[1-g.turn].length} cartas</p><div class="extra-hand">${g.hands[g.turn].map((c,i)=>`<button data-a="select" data-i="${i}" class="${g.discard[g.turn].includes(i)?'selected':''}">${tile(c)}</button>`).join('')}</div>${g.stage==='swap'?'<button data-a="confirm">Confirmar cambio</button>':''}`}
function escoba(g){const names=s=>({Oros:'🪙',Copas:'🏆',Espadas:'⚔️',Bastos:'🪵'}[s]);return `<p class="extra-status">Mesa: ${g.table.map((c,i)=>`<button data-a="table" data-i="${i}" class="${g.sel.includes(i)?'selected':''}">${c.v}${names(c.s)}</button>`).join(' ')||'vacía'} · Capturas J1 ${g.captured[0].length} / J2 ${g.captured[1].length}</p><p>Elige tu carta y las cartas de mesa que sumen 15; si no capturas, juega solo tu carta.</p><div class="extra-hand">${g.hands[g.turn].map((c,i)=>`<button data-a="hand" data-i="${i}" class="${g.card===i?'selected':''}">${c.v}${names(c.s)}</button>`).join('')}</div><button data-a="play">Jugar carta</button>`}
function rummy(g){return `<p class="extra-status">Turno J${g.turn+1} · ${g.message} · Rival: ${g.hands[1-g.turn].length} cartas</p><p>Mazo ${g.deck.length} · Descarte ${tile(g.discard.at(-1))} · Bajadas J1 ${g.melds[0].length} / J2 ${g.melds[1].length}</p><button data-a="stock" ${g.drawn?'disabled':''}>Robar mazo</button><button data-a="top" ${g.drawn?'disabled':''}>Tomar descarte</button><button data-a="meld" ${!g.drawn?'disabled':''}>Bajar grupo</button><p>Tras robar, toca una carta para descartarla.</p><div class="extra-hand">${g.hands[g.turn].map((c,i)=>`<button data-a="discard" data-i="${i}" ${!g.drawn?'disabled':''}>${tile(c)}</button>`).join('')}</div>`}
function render(id,g,ctx){let waiting=ctx.wifi&&ctx.player!==g.turn,html=waiting?'<p class="extra-status">Esperando el turno del otro jugador…</p>':({domino:()=>domino(g),memory:()=>memory(g),dotsboxes:()=>dots(g),stop:()=>stop(g),mahjong:()=>mahjong(g),blackjack:()=>blackjack(g),poker:()=>poker(g),escoba:()=>escoba(g),rummy:()=>rummy(g)})[id]();return {html:`<div class="extra-game">${html}</div>`,bind:()=>bind(id,g,ctx)}}
function win(g,p,msg){g.over=true;g.winner=p;g.message=msg||`Jugador ${p+1} gana.`}
function bind(id,g,ctx){const root=document.querySelector('#miniGameStage');if(!root)return;root.querySelectorAll('[data-a]').forEach(b=>{b.disabled=ctx.wifi&&ctx.player!==g.turn;b.onclick=()=>{if(ctx.wifi&&ctx.player!==g.turn)return;const a=b.dataset.a,i=+b.dataset.i;
 if(id==='domino'){let h=g.hands[g.turn];if(a==='play'){let t=h.splice(i,1);if(!g.row.length){g.row.push(t[0]);g.ends=[t[0][0],t[0][1]]}else if(t[0].includes(g.ends[0])){let v=t[0].indexOf(g.ends[0])===0?t[0][1]:t[0][0];g.row.unshift(t[0]);g.ends[0]=v}else if(t[0].includes(g.ends[1])){let v=t[0].indexOf(g.ends[1])===0?t[0][1]:t[0][0];g.row.push(t[0]);g.ends[1]=v}g.passes=0;if(!h.length)win(g,g.turn);else g.turn=1-g.turn}else if(a==='draw'){if(g.stock.length)h.push(g.stock.pop());g.message='Ficha robada; juega si puedes.'}else if(a==='pass'){g.passes++;g.turn=1-g.turn;if(g.passes>=2||!g.stock.length&&g.hands[g.turn].every(t=>!g.row.length||!t.includes(g.ends[0])&&!t.includes(g.ends[1]))){let n=g.hands.map(x=>x.reduce((s,t)=>s+t[0]+t[1],0));win(g,n[0]===n[1]?g.turn:n[0]<n[1]?0:1,'Partida bloqueada: gana quien tiene menos puntos.')} }g.message=g.message||`Turno del Jugador ${g.turn+1}.`}
 if(id==='memory'){if(a==='tile'){g.open.push(i);if(g.open.length===2){let [x,y]=g.open;if(g.tiles[x].v===g.tiles[y].v){g.tiles[x].gone=g.tiles[y].gone=true;g.pairs[g.turn]++;g.open=[];if(g.pairs[0]+g.pairs[1]===8)win(g,g.pairs[0]===g.pairs[1]?-1:g.pairs[0]>g.pairs[1]?0:1,'Ronda de memoria terminada.')}else g.locked=true}}if(a==='continue'){g.open=[];g.locked=false;g.turn=1-g.turn}}
 if(id==='dotsboxes'&&a==='edge'){let k=b.dataset.k;g.edges[k]=g.turn;let made=[];for(let y=0;y<4;y++)for(let x=0;x<4;x++){let ix=y*4+x,ks=[`h${x},${y}`,`h${x},${y+1}`,`v${x},${y}`,`v${x+1},${y}`];if(g.boxes[ix]<0&&ks.every(z=>g.edges[z]!==undefined))made.push(ix)}made.forEach(ix=>{g.boxes[ix]=g.turn;g.score[g.turn]++});if(Object.keys(g.edges).length===40)win(g,g.score[0]===g.score[1]?-1:g.score[0]>g.score[1]?0:1,'Puntos y cajas · '+g.score.join(' a '));if(!made.length)g.turn=1-g.turn}
 if(id==='stop'){if(a==='answer'){g.answers[g.turn][g.q]=root.querySelector('#stopAnswer').value.trim();if(g.turn===0)g.turn=1;else{g.turn=0;g.q++;if(g.q===10){g.phase='vote';g.turn=0;g.voteIndex=0}else g.message=`Letra ${g.letter} · ${g.questions[g.q]} · tienes 20 segundos.`}g.left=20}if(a==='vote'){g.votes[g.turn][g.voteIndex]=b.dataset.v==='1';if(++g.voteIndex===10){if(g.turn===0){g.turn=1;g.voteIndex=0}else{g.phase='result';g.points=[0,0];for(let q=0;q<10;q++)for(let p=0;p<2;p++){let ans=g.answers[p][q].toLocaleLowerCase();if(g.votes[1-p][q]&&ans.startsWith(g.letter.toLowerCase()))g.points[p]+=ans&&ans===g.answers[1-p][q].toLocaleLowerCase()?5:10}win(g,g.points[0]===g.points[1]?-1:g.points[0]>g.points[1]?0:1,`Puntaje ${g.points[0]}–${g.points[1]}`)}}}if(a==='again')Object.assign(g,create('stop',g.mode))}
 if(id==='mahjong'){if(a==='tile'){g.selected.push(i);if(g.selected.length===2){let [x,y]=g.selected;if(x!==y&&!g.tiles[x].gone&&!g.tiles[y].gone&&g.tiles[x].v===g.tiles[y].v){g.tiles[x].gone=g.tiles[y].gone=true;g.score[g.turn]++;g.message='¡Pareja! Juegas otra vez.';if(g.tiles.every(t=>t.gone))win(g,g.score[0]===g.score[1]?-1:g.score[0]>g.score[1]?0:1,'Duelo Mahjong terminado.')}else{g.turn=1-g.turn;g.message='No coinciden. Cambia el turno.'}g.selected=[]}}}
 if(id==='blackjack'){if(a==='hit'){g.hands[g.turn].push(g.deck.pop());let v=score21(g.hands[g.turn]);if(v>21)g.stood[g.turn]=true}if(a==='stand')g.stood[g.turn]=true;if(g.stood[0]&&g.stood[1]){while(score21(g.dealer)<17)g.dealer.push(g.deck.pop());let v=g.hands.map(score21),d=score21(g.dealer),p=v.map(n=>n>21?0:n>d?2:n===d?1:0);g.stage='done';win(g,p[0]===p[1]?-1:p[0]>p[1]?0:1,`Blackjack · J1 ${v[0]} · J2 ${v[1]} · banca ${d}`)}else if(g.stood[g.turn])g.turn=1-g.turn;g.message=`Puntaje ${score21(g.hands[g.turn])}`}
 if(id==='poker'){if(a==='select'){let d=g.discard[g.turn],at=d.indexOf(i);if(at<0&&d.length<3)d.push(i);else if(at>=0)d.splice(at,1)}if(a==='confirm'){let h=g.hands[g.turn];g.discard[g.turn].sort((x,y)=>y-x).forEach(x=>h.splice(x,1));for(let n=0;n<g.discard[g.turn].length;n++)h.push(g.deck.pop());g.discard[g.turn]=[];if(g.turn===0)g.turn=1;else{let x=rankPoker(g.hands[0]),y=rankPoker(g.hands[1]);win(g,x===y?-1:x>y?0:1,`Mano: J1 ${pokerName(x)} · J2 ${pokerName(y)}`)}g.message=`Jugador ${g.turn+1}: elige hasta tres cartas para cambiar.`}}
 if(id==='escoba'){if(a==='hand')g.card=i;if(a==='table'){let at=g.sel.indexOf(i);if(at<0)g.sel.push(i);else g.sel.splice(at,1)}if(a==='play'&&g.card!==undefined){let h=g.hands[g.turn],c=h[g.card],val=x=>x.v>7?x.v-2:x.v,sum=val(c)+g.sel.reduce((s,x)=>s+val(g.table[x]),0);if(g.sel.length&&sum===15){g.captured[g.turn].push(c,...g.sel.map(x=>g.table[x]));g.table=g.table.filter((_,ix)=>!g.sel.includes(ix));g.last=g.turn}else g.table.push(c);h.splice(g.card,1);g.card=undefined;g.sel=[];if(g.deck.length){if(!g.hands[0].length&&!g.hands[1].length){g.hands[0]=g.deck.splice(0,3);g.hands[1]=g.deck.splice(0,3)}}else if(!g.hands[0].length&&!g.hands[1].length){if(g.last>=0)g.captured[g.last].push(...g.table);win(g,g.captured[0].length===g.captured[1].length?-1:g.captured[0].length>g.captured[1].length?0:1,'Gana quien capturó más cartas.')}g.turn=1-g.turn}}
 if(id==='rummy'){if(a==='stock'&&!g.drawn&&g.deck.length){g.hands[g.turn].push(g.deck.pop());g.drawn=true}if(a==='top'&&!g.drawn&&g.discard.length){g.hands[g.turn].push(g.discard.pop());g.drawn=true}if(a==='meld'&&g.drawn){let m=findMeld(g.hands[g.turn]);if(m){g.hands[g.turn]=g.hands[g.turn].filter(c=>!m.includes(c));g.melds[g.turn].push(...m);g.message=`Jugador ${g.turn+1} bajó una combinación.`;if(!g.hands[g.turn].length)win(g,g.turn,'¡Rummy! Todas las cartas quedaron combinadas.')}else g.message='No hay un grupo válido de 3 o más.'}if(a==='discard'&&g.drawn){g.discard.push(g.hands[g.turn].splice(i,1)[0]);g.drawn=false;if(!g.hands[g.turn].length)win(g,g.turn,'¡Rummy! Te quedaste sin cartas.');else{g.turn=1-g.turn;g.message='Roba una carta y descarta una.'}}}
 ctx.publish();ctx.render()}})}
function score21(h){let n=0,a=0;for(const c of h){if(c.v===1){n+=11;a++}else n+=Math.min(c.v,10)}while(n>21&&a-- >0)n-=10;return n}
function rankPoker(h){let v=h.map(c=>c.v===1?14:c.v).sort((a,b)=>b-a),counts={};v.forEach(x=>counts[x]=(counts[x]||0)+1);let q=Object.values(counts).sort((a,b)=>b-a),flush=h.every(c=>c.s===h[0].s),straight=v.every((x,i)=>i===0||v[i-1]===x+1),r=flush&&straight?9:q[0]===4?8:q[0]===3&&q[1]===2?7:flush?6:straight?5:q[0]===3?4:q[0]===2&&q[1]===2?3:q[0]===2?2:1;return r*1e6+v.reduce((s,x,i)=>s+x*(15**(4-i)),0)}function pokerName(n){return ['','carta alta','pareja','doble pareja','trío','escalera','color','full','póker','escalera de color'][Math.floor(n/1e6)]||'mano'}
function findMeld(h){for(let n=3;n<=h.length;n++){let found=null;function walk(start,a){if(found)return;if(a.length===n){let same=a.every(c=>c.v===a[0].v),v=a.map(c=>c.v).sort((x,y)=>x-y),seq=a.every(c=>c.s===a[0].s)&&new Set(v).size===n&&v.every((x,i)=>!i||x===v[i-1]+1);if(same||seq)found=a;return}for(let i=start;i<h.length;i++)walk(i+1,[...a,h[i]])}walk(0,[]);if(found)return found}return null}
function allMeld(h){if(!h.length)return true;let first=h[0];for(let n=2;n<h.length;n++){let group=[first,...h.slice(1,n+1)],same=group.every(c=>c.v===first.v),seq=group.every(c=>c.s===first.s)&&new Set(group.map(c=>c.v)).size===group.length&&group.map(c=>c.v).sort((a,b)=>a-b).every((v,i,a)=>!i||v===a[i-1]+1);if((same||seq)&&allMeld(h.filter(c=>!group.includes(c))))return true}return false}
window.SudomiExtraGames={create,render,tick(id,g,ctx){if(id==='stop'&&g.phase==='answer'&&(!ctx.wifi||ctx.player===g.turn)){const timer=document.querySelector('#stopTimer');if(--g.left<=0){const root=document.querySelector('#miniGameStage'),b=root?.querySelector('[data-a="answer"]');b?.click()}else if(timer)timer.textContent=g.left}}};
})();
