/* SUDOMI 0.2.5 — five lightweight, playable mini-games */
(()=>{
const $=s=>document.querySelector(s), hub=$('#miniGamesHub'),stage=$('#miniGameStage');
const games=[
 ['mines','💣','Buscaminas','Encuentra las casillas seguras.'],
 ['fleet','🚢','Batalla naval','Hunde la flota rival.'],
 ['chess','♟️','Ajedrez','Un duelo clásico para dos.'],
 ['checkers','🔴','Damas','Captura las piezas contrarias.'],
 ['tictactoe','❌','Tres en raya','Vence a la computadora.'],
 ['connect4','🟡','4 en línea','Conecta cuatro fichas seguidas.'],
 ['domino','🁣','Dominó','Versión para dos jugadores.'],
 ['memory','🐾','Memoria de animales','Encuentra parejas volteando dos fichas.'],
 ['dotsboxes','▫️','Puntos y cajas','Completa cuadros para sumar puntos.'],
 ['stop','🔤','STOP','Diez categorías y votación para dos jugadores.'],
 ['mahjong','🀄','Duelo Mahjong','Variante de emparejar fichas para 2 jugadores.'],
 ['blackjack','🂡','Blackjack','Cartas, estrategia y banca.'],
 ['poker','🃏','Póker','Partidas de cartas para 2–3 jugadores.'],
 ['escoba','🃑','Escoba','La clásica escoba con baraja española.'],
 ['rummy','🎴','Rummy','Forma combinaciones con tus cartas.']
];
let current=null, game=null, wifi={active:false,player:0,handler:null}, acknowledgedWin=null, localWinListener=null;
const matchRecords={tictactoe:{pve:{scores:[0,0],starter:0},pvp:{scores:[0,0],starter:0}},connect4:{pve:{scores:[0,0]},pvp:{scores:[0,0]}}};
function init(){
 $('#openMiniGames').onclick=()=>{let m=$('#homeDropdown');m.classList.add('hidden');$('#homeMenuBtn').setAttribute('aria-expanded','false');open()};
 $('#gamesBackHome').onclick=back;
 setInterval(()=>{if(current==='mines'&&game?.mode==='clock'&&game.clockStarted&&!game.over){game.seconds++;let value=clockText(game.seconds);let timer=$('#mineClock'),badge=document.querySelector('.turn-indicator');if(timer)timer.textContent=value;if(badge)badge.textContent=`⏱ ${value}`}else if(game&&games.findIndex(g=>g[0]===current)>=6)SudomiExtraGames.tick(current,game,{wifi:wifi.active,player:wifi.player,render})},1000);
 renderHub();
}
function open(){ $('#homeScreen').classList.add('hidden');$('#gameScreen').classList.add('hidden');$('#miniGamesScreen').classList.remove('hidden');stage.classList.add('hidden');hub.classList.remove('hidden');renderHub() }
function leaveWifi(){if(wifi.active&&window.SudomiLAN){SudomiLAN.leave();wifi.active=false;wifi.player=0;wifi.handler=null}}
function back(){leaveWifi();stage.classList.add('hidden');hub.classList.remove('hidden');$('#miniGamesScreen').classList.add('hidden');$('#homeScreen').classList.remove('hidden');current=null;game=null;renderHub()}
function toHub(){if(game?.dispose)game.dispose();leaveWifi();current=null;game=null;stage.classList.add('hidden');hub.classList.remove('hidden');renderHub()}
function renderHub(){hub.innerHTML=`<p class="games-intro">Elige un juego y selecciona cómo quieres jugar.</p><div class="games-grid">${games.map(([id,icon,name,desc])=>`<button class="game-card" data-game="${id}"><span>${icon}</span><strong>${name}</strong><small>${desc}</small><b>Elegir modo <i>›</i></b></button>`).join('')}</div>`;hub.querySelectorAll('[data-game]').forEach(b=>b.onclick=()=>chooseMode(b.dataset.game));}
function chooseMode(id){const item=games.find(g=>g[0]===id),extra=games.findIndex(g=>g[0]===id)>=6,choices=id==='mines'?'<button data-mode="clock"><strong>⏱ Contra el reloj</strong><small>Completa el tablero y mejora tu tiempo</small></button><button data-mode="practice"><strong>🧘 Práctica</strong><small>Juega sin cronómetro</small></button>':extra?'<button data-mode="pvp"><strong>👥 Dos jugadores</strong><small>Comparte el dispositivo</small></button><button data-mode="wifi"><strong>📶 Multijugador por Wi‑Fi</strong><small>Juega desde dos teléfonos en la misma red</small></button>':'<button data-mode="pve"><strong>🤖 Contra la computadora</strong><small>Juega contra el sistema</small></button><button data-mode="pvp"><strong>👥 Dos jugadores</strong><small>Comparte el dispositivo y juega localmente</small></button><button data-mode="wifi"><strong>📶 Multijugador por Wi‑Fi</strong><small>Juega desde dos teléfonos en la misma red</small></button>';hub.innerHTML=`<button class="games-back mode-back" id="backToGames">‹ Todos los juegos</button><div class="mode-picker"><span class="mode-game-icon">${item[1]}</span><p>ELIGE TU PARTIDA</p><h2>${item[2]}</h2><div class="mode-choices">${choices}</div></div>`;$('#backToGames').onclick=renderHub;hub.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>b.dataset.mode==='wifi'?wifiLobby(id):launch(id,b.dataset.mode));}
function launch(id,mode='pve'){current=id;wifi.active=mode==='wifi';game=create(id,mode==='wifi'?'pvp':mode);if(wifi.active)game.wifi=true;hub.classList.add('hidden');stage.classList.remove('hidden');render();}
function wifiLobby(id){if(!window.SudomiLAN){hub.innerHTML='<p>No se cargó el módulo de conexión local.</p>';return}const item=games.find(g=>g[0]===id);hub.innerHTML=`<button class="games-back mode-back" id="backToModes">‹ Modos</button><div class="mode-picker wifi-picker"><span class="mode-game-icon">📶</span><p>MULTIJUGADOR LOCAL</p><h2>${item[2]} · Wi‑Fi</h2><div class="wifi-lobby"><button class="primary-action" id="createWifiRoom">Crear sala</button><label for="wifiCode">O únete con el código del otro teléfono</label><input id="wifiCode" maxlength="6" autocomplete="one-time-code" placeholder="ABC123"><button class="secondary-action" id="joinWifiRoom">Unirse</button><p id="wifiStatus">Ambos teléfonos deben estar conectados a la misma Wi‑Fi y abrir esta app desde la dirección local de la PC.</p></div></div>`;$('#backToModes').onclick=()=>{if(SudomiLAN.session)SudomiLAN.leave();wifi.handler=null;chooseMode(id)};$('#createWifiRoom').onclick=async()=>{const status=$('#wifiStatus');try{const s=await SudomiLAN.create(id);status.innerHTML=`Comparte este código con el otro jugador:<strong class="wifi-room-code">${s.room}</strong><span>Esperando que se una…</span>`;startWifiEvents(id)}catch(e){status.textContent=e.message}};$('#joinWifiRoom').onclick=async()=>{const status=$('#wifiStatus'),code=$('#wifiCode').value.trim().toUpperCase();if(code.length!==6){status.textContent='Escribe el código de 6 caracteres.';return}try{const s=await SudomiLAN.join(id,code);wifi.player=s.player;status.textContent='Conectado. Esperando que el creador inicie…';startWifiEvents(id)}catch(e){status.textContent=e.message}}}
function startWifiEvents(id){if(wifi.handler)SudomiLAN.off(wifi.handler);wifi.handler=e=>{if(e.type==='error'){const s=$('#wifiStatus');if(s)s.textContent=e.message;return}if(e.type==='peer-joined'&&SudomiLAN.session?.player===0){wifi.player=0;launch(id,'wifi');wifiSend('start',wifiSnapshot());return}if(e.type==='start'&&SudomiLAN.session?.player===1){wifi.player=1;launch(id,'wifi');applyWifiSnapshot(e.payload);return}if(e.type==='state'&&wifi.active){applyWifiSnapshot(e.payload);render();return}if(e.type==='win-ack'&&wifi.active&&game){acknowledgedWin=game;if(localWinListener){document.removeEventListener('click',localWinListener,true);localWinListener=null}render()}};SudomiLAN.on(wifi.handler)}
function wifiSnapshot(){const state={};for(const k of Object.keys(game))if(!['mode','record','wifi'].includes(k))state[k]=game[k];return {state,scores:game.record?.scores||null,starter:game.record?.starter}}
function applyWifiSnapshot(packet){if(!game||!packet?.state)return;for(const [k,v] of Object.entries(packet.state))game[k]=v;if(packet.scores&&game.record)game.record.scores=packet.scores;if(packet.starter!==undefined&&game.record)game.record.starter=packet.starter}
function wifiSend(type,payload){if(wifi.active&&window.SudomiLAN?.session)SudomiLAN.send(type,payload).catch(e=>console.warn('SUDOMI Wi-Fi:',e.message))}
function publishWifi(){if(wifi.active)wifiSend('state',wifiSnapshot())}
function localTurn(){if(!wifi.active)return true;if(current==='fleet'){if(game.phase==='setup')return game.turn===wifi.player;if(game.phase==='handoff')return game.afterWait==='setup'?game.turn===wifi.player: wifi.player===0;return game.turn===wifi.player}if(current==='chess')return game.turn===(wifi.player===0?'w':'b');if(current==='checkers')return game.turn===(wifi.player===0?'r':'b');if(current==='tictactoe')return game.turn===(wifi.player===0?'X':'O');if(current==='connect4')return game.turn===(wifi.player===0?'R':'Y');if(games.findIndex(g=>g[0]===current)>=6)return game.turn===wifi.player;return false}
function create(id,mode){if(id==='mines')return new Mines(mode);if(id==='fleet')return new Fleet(mode);if(id==='chess')return new Chess(mode);if(id==='checkers')return new Checkers(mode);if(id==='connect4')return new Connect4(mode);if(games.findIndex(g=>g[0]===id)>=6)return SudomiExtraGames.create(id,mode);return new TicTacToe(mode);}
function modeLabel(){return wifi.active?'PVP · WI-FI':game.mode==='pve'?'PVE · CPU':game.mode==='pvp'?'PVP · LOCAL':game.mode==='clock'?'CONTRA EL RELOJ':'PRÁCTICA'}
function isFinished(){return current==='chess'?!!game.done:current==='checkers'?!!game.over:!!game.over}
function resultInfo(){if(!isFinished())return null;let g=game;if(current==='mines')return {title:g.won?'¡Tablero completado!':'Partida terminada',winner:g.won?'Ganador: tú':'Sin ganador · mina descubierta',detail:g.mode==='clock'?`Tiempo: ${clockText(g.seconds)}`:'Modo práctica'};if(current==='fleet')return {title:'Batalla terminada',winner:g.mode==='pve'?(g.won?'Ganador: tú':'Ganador: computadora'):`Ganador: Jugador ${g.won?1:2}`,detail:'Flota hundida'};if(current==='chess'){let draw=g.done.startsWith('Tablas'),white=g.done.includes('ganan blancas');return {title:draw?'Partida en tablas':'Jaque mate',winner:draw?'Sin ganador · tablas':g.mode==='pve'?(white?'Ganador: tú':'Ganador: computadora'):(white?'Ganador: blancas':'Ganador: negras'),detail:g.done}}if(current==='checkers'){let red=g.over.includes('Rojas');return {title:'Partida terminada',winner:g.mode==='pve'?(red?'Ganador: tú':'Ganador: computadora'):(red?'Ganador: rojas':'Ganador: negras'),detail:g.over}}if(current==='tictactoe')return {title:'Partida terminada',winner:g.winner||'Empate',detail:'Tres en raya'};if(current==='connect4')return {title:'Partida terminada',winner:g.winner||'Empate',detail:'4 en línea'};if(games.findIndex(x=>x[0]===current)>=6)return {title:'Partida terminada',winner:g.winner<0?'Empate':`Ganador: Jugador ${g.winner+1}`,detail:g.message||games.find(x=>x[0]===current)[2]};return null}
function winnerPlayer(){if(current==='fleet')return game.won?0:1;if(current==='chess')return game.done.includes('ganan blancas')?0:1;if(current==='checkers')return game.over.includes('Rojas')?0:1;if(current==='tictactoe')return game.winnerLine?.length&&game.b[game.winnerLine[0]]==='X'?0:1;if(current==='connect4')return game.winnerLine?.length&&game.b[game.winnerLine[0]]==='R'?0:1;if(games.findIndex(g=>g[0]===current)>=6)return game.winner;return null}
function victoryPrompt(result){if(wifi.active)return wifi.player===winnerPlayer()?`¡${result.winner}! Espera a que quien perdió toque su pantalla para ver el resultado.`:'Toca cualquier parte de la pantalla para detener la animación y ver el resultado.';return 'Pásale el dispositivo a quien perdió. Cuando esté listo, toca cualquier parte de la pantalla.'}
function localWinPending(result=resultInfo()){return !!(game&&game.mode==='pvp'&&result&&!/empate|sin ganador/i.test(result.winner)&&acknowledgedWin!==game)}
function armLocalWinTap(waiting){if(!waiting){if(localWinListener){document.removeEventListener('click',localWinListener,true);localWinListener=null}return}if(localWinListener)return;const target=game;localWinListener=e=>{if(game!==target)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();if(wifi.active&&wifi.player===winnerPlayer())return;acknowledgedWin=target;document.removeEventListener('click',localWinListener,true);localWinListener=null;if(wifi.active)wifiSend('win-ack');render()};document.addEventListener('click',localWinListener,true)}
function turnInfo(){if(current==='mines')return game.mode==='clock'?`⏱ ${clockText(game.seconds)}`:game.mode==='practice'?'🧩 Práctica':'';if(current==='fleet')return game.mode==='pve'?'🎯 Tu turno':`🚢 J${game.turn+1}`;if(current==='chess')return `${game.turn==='w'?'♔':'♚'} ${game.mode==='pve'&&game.turn==='b'?'CPU':game.turn==='w'?'Blancas':'Negras'}`;if(current==='checkers')return `${game.turn==='r'?'🔴':'⚫'} ${game.mode==='pve'&&game.turn==='b'?'CPU':game.turn==='r'?'Rojas':'Negras'}`;if(current==='tictactoe')return `${game.turn==='X'?'❌':'⭕'} ${game.mode==='pve'&&game.turn==='O'?'CPU':`Jugador ${game.turn==='X'?1:2}`}`;if(current==='connect4')return `${game.turn==='R'?'🔴':'🟡'} ${game.mode==='pve'&&game.turn==='Y'?'CPU':game.turn==='R'?'Rojo · J1':'Amarillo · J2'}`;if(games.findIndex(g=>g[0]===current)>=6)return `🎲 Jugador ${game.turn+1}`;return ''}
function clockText(s){return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function resetMatch(){if(wifi.active&&wifi.player!==0)return;const mode=wifi.active?'pvp':game.mode;game=create(current,mode);if(wifi.active)game.wifi=true;render();publishWifi()}
function shell(title,subtitle,content){const result=resultInfo(),waiting=localWinPending(result),score=current==='tictactoe'||current==='connect4'?game.scoreMarkup():'';stage.innerHTML=`<div class="mini-game ${waiting?'local-win-active':''}"><div class="mini-game-head"><div><p>ARCADE SUDOMI · ${modeLabel()}</p><h2>${title}</h2><small>${subtitle}</small></div><div class="mini-game-actions"><span class="turn-indicator">${turnInfo()}</span><button class="game-restart" id="gameListBtn">Juegos</button><button class="game-restart" id="sudokuBtn">Sudoku</button><button class="game-restart" id="changeMode">Modos</button>${score?'<button class="game-restart" id="resetScore">Reiniciar marcador</button>':''}<button class="game-restart" id="restartMini" ${wifi.active&&wifi.player!==0?'disabled title="El creador de la sala reinicia la partida"':''}>↻</button></div></div>${waiting?`<p class="victory-awaiting"><strong>🏆 ${result.winner}</strong><span>${victoryPrompt(result)}</span></p>`:''}${score}${content}${result&&!waiting?`<div class="game-end-overlay"><div class="game-end-card"><p>PARTIDA TERMINADA</p><h3>${result.title}</h3><strong>${result.winner}</strong><small>${result.detail}</small><div><button id="playAgain" ${wifi.active&&wifi.player!==0?'disabled':''}>Jugar otra</button><button id="endGames">Todos los juegos</button><button id="endSudoku">Volver a Sudoku</button></div></div></div>`:''}</div>`;$('#restartMini').onclick=()=>wifi.active?resetMatch():(game=create(current,game.mode),render());const reset=$('#resetScore');if(reset)reset.onclick=()=>{game.record.scores=[0,0];publishWifi();render()};$('#gameListBtn').onclick=toHub;$('#sudokuBtn').onclick=back;$('#changeMode').onclick=()=>{if(wifi.active)leaveWifi();game=null;stage.classList.add('hidden');hub.classList.remove('hidden');chooseMode(current)};if(result&&!waiting){$('#playAgain').onclick=resetMatch;$('#endGames').onclick=toHub;$('#endSudoku').onclick=back}armLocalWinTap(waiting)}
function render(){if(current==='mines')renderMines();else if(current==='fleet')renderFleet();else if(current==='chess')renderChess();else if(current==='checkers')renderCheckers();else if(current==='connect4')renderConnect4();else if(games.findIndex(g=>g[0]===current)>=6){const x=SudomiExtraGames.render(current,game,{wifi:wifi.active,player:wifi.player,publish:publishWifi,render});shell(games.find(g=>g[0]===current)[2],game.message||'Toma tu turno',x.html);x.bind()}else renderTtt();}

// Minesweeper: 9×9 beginner board, safe first click, flags and recursive reveal.
class Mines{
 constructor(mode='clock'){this.mode=mode;this.seconds=0;this.clockStarted=false;this.n=9;this.total=10;this.m=Array(81).fill(false);this.opened=Array(81).fill(false);this.flags=Array(81).fill(false);this.ready=false;this.over=false;this.won=false;this.flagMode=false}
 neighbors(i){let r=i/9|0,c=i%9;let out=[];for(let y=-1;y<=1;y++)for(let x=-1;x<=1;x++){let a=r+y,b=c+x;if((x||y)&&a>=0&&a<9&&b>=0&&b<9)out.push(a*9+b)}return out}
 setup(safe){let picks=Array.from({length:81},(_,i)=>i).filter(i=>i!==safe).sort(()=>Math.random()-.5).slice(0,10);picks.forEach(i=>this.m[i]=true);this.ready=true}
 count(i){return this.neighbors(i).filter(j=>this.m[j]).length}
 reveal(i){if(this.over||this.flags[i]||this.opened[i])return;if(!this.ready)this.setup(i);if(this.mode==='clock')this.clockStarted=true;if(this.m[i]){this.over=true;return}this.opened[i]=true;if(!this.count(i))this.neighbors(i).forEach(j=>this.reveal(j));if(this.opened.filter((v,j)=>v&&!this.m[j]).length===71){this.over=true;this.won=true}}
 flag(i){if(!this.over&&!this.opened[i])this.flags[i]=!this.flags[i]}
}
function renderMines(){let g=game,status=g.over?(g.won?'¡Tablero despejado! 🎉':'¡Mina descubierta!'):g.mode==='clock'?`Tiempo ${clockText(g.seconds)} · Minas ${g.flags.filter(Boolean).length}/${g.total}`:`Modo práctica · Minas ${g.flags.filter(Boolean).length}/${g.total}`;shell('Buscaminas',status,`<div class="game-tools"><span class="mine-clock">${g.mode==='clock'?'⏱ <b id="mineClock">'+clockText(g.seconds)+'</b>':'Sin cronómetro'}</span><button id="flagMode" class="mini-tool ${g.flagMode?'on':''}">🚩 ${g.flagMode?'Modo bandera activado':'Marcar bandera'}</button></div><div class="mine-grid">${g.m.map((mine,i)=>{let shown=g.opened[i]||g.over&&mine;let count=g.count(i);let text=g.flags[i]?'🚩':shown?(mine?'💣':count||''):'';return `<button class="mine-cell ${shown&&!mine?'revealed':''} ${mine&&g.over?'mine-hit':''}" data-i="${i}" ${g.opened[i]||g.over?'disabled':''}>${text}</button>`}).join('')}</div><p class="board-hint">Primer toque seguro · revela todas las casillas sin minas. En móvil activa “Marcar bandera” para 🚩</p>`);$('#flagMode').onclick=()=>{g.flagMode=!g.flagMode;render()};stage.querySelectorAll('.mine-cell').forEach(b=>{const i=+b.dataset.i;b.onclick=()=>{if(g.flagMode)g.flag(i);else g.reveal(i);render()};b.oncontextmenu=e=>{e.preventDefault();g.flag(i);render()}})}

// Battleship: fleet hidden from the computer; the computer fires back automatically.
class Fleet{
 constructor(mode='pve'){this.mode=mode;this.n=8;this.fleet=[{name:'Acorazado',len:4},{name:'Crucero',len:3},{name:'Submarino',len:3},{name:'Patrullera',len:2}];this.you=Array(64).fill(false);this.enemy=Array(64).fill(false);this.remaining=[this.fleet.map(x=>x.len),this.fleet.map(x=>x.len)];this.placed=[[],[]];this.shots=Array(64).fill(false);this.shots2=Array(64).fill(false);this.incoming=Array(64).fill(false);this.turn=0;this.phase='setup';this.afterWait='';this.waiting=false;this.orientation='h';this.selectedLength=4;this.lastShot='';this.lastShotIndex=-1;this.over=false;this.won=false;this.setSelected()}
 get board(){return this.turn===0?this.you:this.enemy}
 get remainingHere(){return this.remaining[this.turn]}
 setSelected(){if(!this.remainingHere.includes(this.selectedLength))this.selectedLength=[...this.remainingHere].sort((a,b)=>b-a)[0]||0}
 placementCells(i){let r=i/8|0,c=i%8,len=this.selectedLength,ids=Array.from({length:len},(_,k)=>this.orientation==='h'?r*8+c+k:(r+k)*8+c);return ids.some((x,k)=>x>=64||this.orientation==='h'&&(x%8)<c||this.board[x])?[]:ids}
 placeAt(i){if(this.phase!=='setup')return;let ids=this.placementCells(i);if(!ids.length)return;ids.forEach(x=>this.board[x]=true);this.placed[this.turn].push({len:this.selectedLength,ids});this.remainingHere.splice(this.remainingHere.indexOf(this.selectedLength),1);this.setSelected();if(!this.remainingHere.length){if(this.mode==='pve'){this.randomFleet(this.enemy);this.phase='play';this.turn=0;this.lastShot='Tu flota está lista. ¡A disparar!'}else if(this.turn===0){this.turn=1;this.selectedLength=4;this.phase='handoff';this.afterWait='setup';this.waiting=true}else{this.turn=0;this.phase='handoff';this.afterWait='play';this.waiting=true}}}
 undoPlacement(){if(this.phase!=='setup')return;let p=this.placed[this.turn].pop();if(!p)return;p.ids.forEach(i=>this.board[i]=false);this.remainingHere.push(p.len);this.selectedLength=p.len}
 randomFleet(board){for(const ship of this.fleet){let done=false,tries=0;while(!done&&tries++<1000){let horizontal=Math.random()<.5,r=Math.random()*8|0,c=Math.random()*8|0,ids=Array.from({length:ship.len},(_,k)=>horizontal?r*8+c+k:(r+k)*8+c);if(ids.some(x=>x>=64||horizontal&&x%8<c||board[x]))continue;ids.forEach(x=>board[x]=true);done=true}}}
 ready(){this.waiting=false;this.phase=this.afterWait;this.afterWait='';this.lastShot=''}
 passTurn(){this.turn=1-this.turn;this.phase='handoff';this.afterWait='play';this.waiting=true;this.lastShot=''}
 fire(i){if(this.over||this.phase!=='play')return;if(this.mode==='pvp'){let attacks=this.turn===0?this.shots:this.shots2,targets=this.turn===0?this.enemy:this.you;if(attacks[i])return;attacks[i]=true;this.lastShotIndex=i;this.lastShot=targets[i]?'¡Tocado!':'Agua';if(targets.filter((v,j)=>v&&attacks[j]).length===12){this.over=true;this.won=this.turn===0;return}this.phase='result';return}if(this.shots[i])return;this.shots[i]=true;this.lastShotIndex=i;this.lastShot=this.enemy[i]?'¡Tocado!':'Agua';if(this.enemy.filter((v,j)=>v&&this.shots[j]).length===12){this.over=true;this.won=true;return}let choices=this.incoming.map((v,j)=>v?-1:j).filter(j=>j>=0);if(choices.length){let c=choices[Math.random()*choices.length|0];this.incoming[c]=true}if(this.you.filter((v,j)=>v&&this.incoming[j]).length===12){this.over=true;this.won=false}}
}
function renderFleet(){let g=game,celebrate=localWinPending();if(g.phase==='setup'){let setupPlayer=`Jugador ${g.turn+1}`;let cells=g.board.map((occupied,i)=>`<button class="fleet-cell setup-cell ${occupied?'your-ship':''}" data-i="${i}" ${occupied||!g.selectedLength||!localTurn()?'disabled':''}></button>`).join('');shell('Batalla naval',`Coloca los barcos · ${setupPlayer}`,`<div class="fleet-setup-tools"><div class="ship-choice-list">${[...new Set(g.fleet.map(s=>s.len))].map(len=>{let s=g.fleet.find(x=>x.len===len),qty=g.remainingHere.filter(x=>x===len).length;return `<button class="ship-choice ${qty?'':'used'} ${g.selectedLength===len?'selected':''}" data-len="${len}" ${!qty||!localTurn()?'disabled':''}>${len===3?'Crucero / submarino':s.name}<small>${len} casillas · ${qty} disponibles</small></button>`}).join('')}</div><button id="rotateShip" class="mini-tool" ${!localTurn()?'disabled':''}>↻ Girar barco (${g.orientation==='h'?'horizontal':'vertical'})</button></div><div class="fleet-placement-grid">${cells}</div><p class="board-hint">Elige un barco, ajusta la orientación y toca el tablero para colocarlo. Evita que se salga o se cruce con otro barco.</p>`);stage.querySelectorAll('.ship-choice').forEach(b=>b.onclick=()=>{if(!localTurn())return;g.selectedLength=+b.dataset.len;render()});$('#rotateShip').onclick=()=>{if(!localTurn())return;g.orientation=g.orientation==='h'?'v':'h';render()};const undo=document.createElement('button');undo.className='mini-tool undo-ship';undo.textContent='↶ Deshacer último barco';undo.disabled=!g.placed[g.turn].length||!localTurn();undo.onclick=()=>{if(!localTurn())return;g.undoPlacement();render()};$('#rotateShip').insertAdjacentElement('afterend',undo);stage.querySelectorAll('.setup-cell:not(:disabled)').forEach(b=>{b.onclick=()=>{if(!localTurn())return;g.placeAt(+b.dataset.i);if(wifi.active&&g.phase==='handoff')publishWifi();render()};b.onmouseenter=()=>{let ids=g.placementCells(+b.dataset.i);stage.querySelectorAll('.setup-cell').forEach(x=>{if(ids.includes(+x.dataset.i))x.classList.add('preview')})};b.onmouseleave=()=>stage.querySelectorAll('.setup-cell').forEach(x=>x.classList.remove('preview'))});return}
 if(g.phase==='handoff'){let title=g.afterWait==='setup'?`Jugador ${g.turn+1}, prepara tu flota`:'¡Las flotas están listas!';shell('Batalla naval',title,`<div class="pass-device"><span>🔒</span><h3>${g.afterWait==='setup'?'Entrega el dispositivo':'Batalla naval lista'}</h3><p>${g.afterWait==='setup'?`Jugador ${g.turn+1}, coloca tus barcos en secreto.`:'Jugador 1, puedes comenzar la batalla.'}</p><button id="readyFleet" class="primary-action" ${!localTurn()?'disabled':''}>${g.afterWait==='setup'?'Estoy listo':'Comenzar partida'}</button></div>`);$('#readyFleet').onclick=()=>{if(!localTurn())return;g.ready();publishWifi();render()};return}
 let attacks=g.turn===0?g.shots:g.shots2,target=g.turn===0?g.enemy:g.you,status=g.mode==='pve'?g.lastShot||'Tu turno':`Jugador ${g.turn+1} · ${g.lastShot||'Elige dónde disparar'}`;let own=g.you.map((ship,i)=>`<span class="fleet-cell ${ship?'your-ship':''} ${g.incoming[i]?(ship?'hit':'miss'):' '}">${g.incoming[i]?(ship?'✹':'·'):''}</span>`).join('');let content=`<div class="fleet-battle ${g.mode==='pvp'?'fleet-single':''}"><div class="fleet-target"><h3>${g.mode==='pve'?'Flota rival':`Objetivo · Jugador ${g.turn===0?2:1}`} · ${target.filter((v,i)=>v&&attacks[i]).length}/12</h3><div class="fleet-grid enemy-grid">${target.map((_,i)=>`<button class="fleet-cell ${attacks[i]?(target[i]?'hit':'miss'):''} ${celebrate&&g.lastShotIndex===i?'winning-shot':''}" data-i="${i}" ${attacks[i]||g.over||g.phase!=='play'||!localTurn()?'disabled':''}>${attacks[i]?(target[i]?'✹':'·'):''}</button>`).join('')}</div></div>${g.mode==='pve'?`<div><h3>Tu flota</h3><div class="fleet-grid own-grid">${own}</div></div>`:''}</div>${g.lastShot?`<p class="shot-feedback ${g.lastShot.includes('Tocado')?'hit-feedback':'miss-feedback'}">${g.lastShot}</p>`:''}${!wifi.active&&g.phase==='result'?'<button id="passFleet" class="primary-action pass-next">Pasar dispositivo al siguiente jugador</button>':''}<p class="board-hint">${wifi.active?'La partida se sincroniza por la red local.':g.mode==='pvp'?'El resultado queda visible antes de pasar el dispositivo.':'La computadora responde a cada disparo.'}</p>`;shell('Batalla naval',status,content);if(g.phase==='result')$('#passFleet')?.addEventListener('click',()=>{g.passTurn();render()});stage.querySelectorAll('.enemy-grid button').forEach(b=>b.onclick=()=>{if(!localTurn())return;g.fire(+b.dataset.i);if(wifi.active&&g.phase==='result'&&!g.over){g.turn=1-g.turn;g.phase='play'}publishWifi();render()})}

// Tic-tac-toe: player X versus a computer that takes wins, blocks, or picks randomly.
class TicTacToe{
 constructor(mode='pve'){this.mode=mode;this.record=matchRecords.tictactoe[mode];this.start=this.record.starter;this.b=Array(9).fill('');this.turn=this.start===0?'X':'O';this.over=false;this.winner='';this.winnerLine=[];this.message=mode==='pve'?(this.turn==='X'?'Tu turno · eres X':'La computadora inicia · eres O'):`Turno de ${this.turn} · Jugador ${this.turn==='X'?1:2}`;if(mode==='pve'&&this.turn==='O'){this.b[4]='O';this.turn='X';this.message='La computadora comenzó · tu turno'}}
 wins=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]]
 winningLine(p){return this.wins.find(line=>line.every(i=>this.b[i]===p))||[]}
 won(p){return this.winningLine(p).length>0}
 finish(side){this.over=true;this.record.starter=1-this.start;this.winnerLine=side?this.winningLine(side):[];if(side){if(this.mode==='pvp'){let n=side==='X'?0:1;this.record.scores[n]++;this.winner=`Gana Jugador ${n+1}`}else{let n=side==='X'?0:1;this.record.scores[n]++;this.winner=n===0?'Ganas tú':'Gana la computadora'}this.message=this.winner}else{this.winner='Empate';this.message='Empate.'}}
 move(i){if(this.over||this.b[i])return;if(this.mode==='pvp'){this.b[i]=this.turn;if(this.won(this.turn)){this.finish(this.turn);return}if(this.b.every(Boolean)){this.finish(null);return}this.turn=this.turn==='X'?'O':'X';this.message=`Turno de ${this.turn} · Jugador ${this.turn==='X'?1:2}`;return}this.b[i]='X';if(this.won('X')){this.finish('X');return}if(this.b.every(Boolean)){this.finish(null);return}this.turn='O';let m=this.best('O')??this.best('X');if(m===null||m===undefined){let a=this.b.map((v,j)=>v?-1:j).filter(j=>j>=0);m=a[Math.random()*a.length|0]}this.b[m]='O';if(this.won('O')){this.finish('O')}else if(this.b.every(Boolean)){this.finish(null)}else{this.turn='X';this.message='Tu turno · eres X'}}
 best(p){for(const line of this.wins){let empty=line.filter(i=>!this.b[i]);if(empty.length===1&&line.filter(i=>this.b[i]===p).length===2)return empty[0]}return null}
 scoreMarkup(){let s=this.record.scores;return `<div class="match-score"><span>${this.mode==='pve'?'Tú':'Jugador 1'}<b>${s[0]}</b></span><i>VS</i><span>${this.mode==='pve'?'Computadora':'Jugador 2'}<b>${s[1]}</b></span></div>`}
}
function renderTtt(){let g=game,celebrate=localWinPending();shell('Tres en raya',g.message,`<div class="ttt-board-wrap"><div class="ttt-board">${g.b.map((v,i)=>`<button class="ttt-cell ${v==='X'?'mark-x':v==='O'?'mark-o':''} ${celebrate&&g.winnerLine.includes(i)?'winning-cell':''}" style="--win-delay:${Math.max(0,g.winnerLine.indexOf(i))*90}ms" data-i="${i}" ${v||g.over||!localTurn()?'disabled':''}><span class="ttt-mark">${v}</span></button>`).join('')}</div></div><p class="board-hint">${g.mode==='pve'?'Juegas contra la computadora. Empieza X.':wifi.active?`Estás jugando como Jugador ${wifi.player+1}.`:'X: Jugador 1 · O: Jugador 2.'}</p>`);stage.querySelectorAll('.ttt-cell').forEach(b=>b.onclick=()=>{if(!localTurn())return;g.move(+b.dataset.i);publishWifi();render()})}

// Connect Four: local two-player or a simple win/block/center-preferring CPU.
class Connect4{
 constructor(mode='pve'){this.mode=mode;this.record=matchRecords.connect4[mode];this.b=Array(42).fill('');this.turn='R';this.busy=false;this.over=false;this.winner='';this.lastMove=-1;this.msg=mode==='pve'?'Tu turno · fichas rojas':'Turno de rojas · Jugador 1'}
 drop(col,side=this.turn){for(let r=5;r>=0;r--){let i=r*7+col;if(!this.b[i]){this.b[i]=side;if(side===this.turn)this.lastMove=i;return i}}return -1}
 winningLine(side){for(let r=0;r<6;r++)for(let c=0;c<7;c++){let i=r*7+c;if(this.b[i]!==side)continue;for(let [dr,dc] of [[0,1],[1,0],[1,1],[1,-1]]){let cells=[0,1,2,3].map(k=>(r+dr*k)*7+c+dc*k);if(cells.every((x,k)=>{let rr=r+dr*k,cc=c+dc*k;return rr>=0&&rr<6&&cc>=0&&cc<7&&this.b[x]===side}))return cells}}return []}
 check(side){return this.winningLine(side).length>0}
 finish(side){this.over=true;this.winnerLine=side?this.winningLine(side):[];if(side){let n=this.mode==='pvp'?(side==='R'?0:1):(side==='R'?0:1);this.record.scores[n]++;this.winner=this.mode==='pve'?(n===0?'Ganas tú':'Gana la computadora'):`Gana Jugador ${n+1}`;this.msg=this.winner}else{this.winner='Empate';this.msg='Empate.'}}
 play(col){if(this.over||this.busy||this.b[col])return;let i=this.drop(col);if(i<0)return;if(this.check(this.turn)){this.finish(this.turn);return}if(this.b.every(Boolean)){this.finish(null);return}if(this.mode==='pvp'){this.turn=this.turn==='R'?'Y':'R';this.msg=`Turno de ${this.turn==='R'?'rojas · Jugador 1':'amarillas · Jugador 2'}`;return}this.turn='Y';this.busy=true;this.msg='La computadora está pensando…';const self=this;setTimeout(()=>{if(game!==self||self.over)return;let colAI=self.choose();self.drop(colAI,'Y');if(self.check('Y'))self.finish('Y');else if(self.b.every(Boolean))self.finish(null);else{self.turn='R';self.msg='Tu turno · fichas rojas'}self.busy=false;render()},400)}
 choose(){let available=Array.from({length:7},(_,c)=>c).filter(c=>!this.b[c]);for(let side of ['Y','R'])for(let c of available){let i=this.drop(c,side),win=this.check(side);this.b[i]='';if(win)return c}return available.sort((a,b)=>Math.abs(a-3)-Math.abs(b-3))[0]}
 scoreMarkup(){let s=this.record.scores;return `<div class="match-score"><span>${this.mode==='pve'?'Tú · Rojo':'Jugador 1 · Rojo'}<b>${s[0]}</b></span><i>VS</i><span>${this.mode==='pve'?'CPU · Amarillo':'Jugador 2 · Amarillo'}<b>${s[1]}</b></span></div>`}
}
function renderConnect4(){let g=game,celebrate=localWinPending();shell('4 en línea',g.busy?'La computadora está pensando…':g.msg,`<div class="connect-board">${Array.from({length:42},(_,i)=>{let r=i/7|0,c=i%7,v=g.b[i],blocked=g.over||g.busy||g.b[c]||!localTurn();return `<button class="connect-slot ${v==='R'?'red-disc':v==='Y'?'yellow-disc':''} ${g.lastMove===i?'falling-disc':''} ${celebrate&&g.winnerLine.includes(i)?'winning-disc':''}" data-col="${c}" ${blocked?'disabled':''} aria-label="Fila ${r+1}, columna ${c+1}${v?`, ficha ${v==='R'?'roja':'amarilla'}`:''}">${v?'●':''}</button>`}).join('')}</div><p class="board-hint">${g.mode==='pve'?'Tú: rojo · Computadora: amarillo':wifi.active?`Estás jugando como Jugador ${wifi.player+1}.`:'Rojo: Jugador 1 · Amarillo: Jugador 2'}</p>`);stage.querySelectorAll('.connect-slot:not(:disabled)').forEach(b=>b.onclick=()=>{if(!localTurn())return;g.play(+b.dataset.col);publishWifi();render()})}

// Checkers: local two-player, diagonal movement, captures, kings and chained jumps.
class Checkers{
 constructor(mode='pve'){this.mode=mode;this.busy=false;this.captured=[[],[]];this.b=Array(64).fill('');for(let r=0;r<3;r++)for(let c=0;c<8;c++)if((r+c)%2)this.b[r*8+c]='b';for(let r=5;r<8;r++)for(let c=0;c<8;c++)if((r+c)%2)this.b[r*8+c]='r';this.turn='r';this.sel=-1;this.moves=[];this.over='';this.msg=mode==='pve'?'Rojas contra negras de la computadora.':'Rojas comienzan · pasan el dispositivo.'}
 captures(side=this.turn){let out=[];for(let i=0;i<64;i++)if(this.b[i]&&this.b[i].toLowerCase()===side)out.push(...this.legal(i).filter(m=>m.capture));return out}
 legal(i){let p=this.b[i];if(!p)return[];let r=i/8|0,c=i%8,dirs=p===p.toUpperCase()?[-1,1]:p==='r'?[-1]:[1],out=[];for(let dr of dirs)for(let dc of [-1,1]){let rr=r+dr,cc=c+dc;if(rr<0||rr>7||cc<0||cc>7)continue;let j=rr*8+cc;if(!this.b[j])out.push({to:j});else if(this.b[j].toLowerCase()!==p.toLowerCase()){let r2=rr+dr,c2=cc+dc;if(r2>=0&&r2<8&&c2>=0&&c2<8&&!this.b[r2*8+c2])out.push({to:r2*8+c2,capture:j})}}return out}
 click(i){if(this.over)return;if(this.sel>=0){let m=this.moves.find(x=>x.to===i);if(m){let p=this.b[this.sel];this.b[i]=p;this.b[this.sel]='';if(m.capture){let taken=this.b[m.capture];this.captured[taken.toLowerCase()==='r'?0:1].push(taken);this.b[m.capture]=''}if(p==='r'&&((i/8)|0)===0)this.b[i]='R';if(p==='b'&&((i/8)|0)===7)this.b[i]='B';if(m.capture&&this.legal(i).some(x=>x.capture)){this.sel=i;this.moves=this.legal(i).filter(x=>x.capture);this.msg='¡Captura otra vez con la misma ficha!';return}this.turn=this.turn==='r'?'b':'r';this.sel=-1;this.moves=[];let stuck=!this.b.some((piece,j)=>piece&&piece.toLowerCase()===this.turn&&this.legal(j).length);if(stuck){this.over=this.turn==='r'?'Negras ganan.':'Rojas ganan.';this.msg=this.over}else this.msg=`Turno de ${this.turn==='r'?'rojas 🔴':'negras ⚫'}`;if(this.mode==='pve'&&this.turn==='b')this.computer();return}}if(this.b[i]&&this.b[i].toLowerCase()===this.turn){let legal=this.legal(i),must=this.captures();if(must.length)legal=legal.filter(x=>x.capture);if(legal.length){this.sel=i;this.moves=legal}}}
 computer(){this.busy=true;const self=this;setTimeout(()=>{if(game!==self||self.over)return;let all=[];for(let i=0;i<64;i++)if(self.b[i]==='b'||self.b[i]==='B')all.push(...self.legal(i).map(m=>({from:i,...m})));let captures=all.filter(m=>m.capture);if(captures.length)all=captures;if(!all.length){self.over='Rojas ganan.';self.msg=self.over}else{let m=all[Math.random()*all.length|0];self.sel=m.from;self.moves=self.legal(m.from);self.click(m.to);while(self.sel>=0&&!self.over){let chain=self.moves[Math.random()*self.moves.length|0];if(!chain)break;self.click(chain.to)}}self.busy=false;render()},350)}
}
function renderCheckers(){let g=game,title=g.busy?'Turno de la computadora…':g.over||g.msg,celebrate=localWinPending(),winningSide=g.over?.startsWith('Rojas')?'r':'b';const tray=(n,color)=>`<aside class="captured-tray ${color}"><strong>${color==='red-captures'?'🔴':'⚫'}</strong><small>${n.length} capturadas</small><div>${n.map(p=>`<i class="captured-piece ${color}">${p===p.toUpperCase()?'♛':'●'}</i>`).join('')}</div></aside>`;shell('Damas',title,`<div class="checkers-layout">${tray(g.captured[0],'red-captures')}<div class="checkers-board">${g.b.map((p,i)=>{let dark=((i/8|0)+i%8)%2===1,move=g.moves.some(m=>m.to===i),cap=g.moves.some(m=>m.to===i&&m.capture);return `<button class="checker-cell ${dark?'dark-square':'light-square'} ${i===g.sel?'chosen':''} ${move?'possible':''} ${cap?'capture-target':''}" data-i="${i}" aria-label="${p?pieceName(p):'casilla'}" ${g.busy||!localTurn()?'disabled':''}>${p?`<span class="checker-piece ${p.toLowerCase()==='r'?'red-piece':'black-piece'} ${celebrate&&p.toLowerCase()===winningSide?'winning-piece':''}">${p===p.toUpperCase()?'<b>♛</b>':''}</span>`:''}</button>`}).join('')}</div>${tray(g.captured[1],'black-captures')}</div><p class="board-hint">${wifi.active?`Estás jugando como Jugador ${wifi.player+1}. `:''}Rojas 🔴 vs negras ⚫ · captura obligatoria · coronación automática.</p>`);stage.querySelectorAll('.checker-cell').forEach(b=>b.onclick=()=>{if(!localTurn())return;g.click(+b.dataset.i);publishWifi();render()})}
function pieceName(p){return p.toLowerCase()==='r'?'Ficha roja':'Ficha negra'}

// Chess: standard local two-player movement, check, checkmate, stalemate, castling, queen promotion.
const INIT_CHESS=['rnbqkbnr','pppppppp','........','........','........','........','PPPPPPPP','RNBQKBNR'];
class Chess{
 constructor(mode='pve'){this.mode=mode;this.busy=false;this.b=INIT_CHESS.join('').split('').map(x=>x==='.'?'':x);this.turn='w';this.sel=-1;this.moves=[];this.done='';this.msg=mode==='pve'?'Blancas vs computadora · tu turno.':'Juegan blancas · pasan el dispositivo.';this.castle={K:true,Q:true,k:true,q:true}}
 color(p){return p===p.toUpperCase()?'w':'b'}
 at(r,c){return r<0||r>7||c<0||c>7?-1:r*8+c}
 pseudo(i,attacksOnly=false){let p=this.b[i];if(!p)return[];let w=this.color(p)==='w',r=i/8|0,c=i%8,k=p.toLowerCase(),out=[],add=(rr,cc)=>{let j=this.at(rr,cc);if(j>=0&&(attacksOnly||!this.b[j]||this.color(this.b[j])!==this.color(p)))out.push(j)};
  if(k==='p'){let d=w?-1:1;if(attacksOnly){add(r+d,c-1);add(r+d,c+1)}else{if(this.at(r+d,c)>=0&&!this.b[this.at(r+d,c)]){out.push(this.at(r+d,c));let start=w?6:1;if(r===start&&!this.b[this.at(r+2*d,c)])out.push(this.at(r+2*d,c))}for(let dc of [-1,1]){let j=this.at(r+d,c+dc);if(j>=0&&this.b[j]&&this.color(this.b[j])!==this.color(p))out.push(j)}}return out}
  if(k==='n'){for(let [dr,dc] of [[-2,-1],[-2,1],[-1,-2],[-1,2],[1,-2],[1,2],[2,-1],[2,1]])add(r+dr,c+dc);return out}
  if(k==='k'){for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++)if(dr||dc)add(r+dr,c+dc);if(!attacksOnly&&w&&r===7&&c===4){if(this.castle.K&&!this.b[61]&&!this.b[62]&&this.b[63]==='R'&&!this.attacked(60,'b')&&!this.attacked(61,'b')&&!this.attacked(62,'b'))out.push(62);if(this.castle.Q&&!this.b[59]&&!this.b[58]&&!this.b[57]&&this.b[56]==='R'&&!this.attacked(60,'b')&&!this.attacked(59,'b')&&!this.attacked(58,'b'))out.push(58)}if(!attacksOnly&&!w&&r===0&&c===4){if(this.castle.k&&!this.b[5]&&!this.b[6]&&this.b[7]==='r'&&!this.attacked(4,'w')&&!this.attacked(5,'w')&&!this.attacked(6,'w'))out.push(6);if(this.castle.q&&!this.b[3]&&!this.b[2]&&!this.b[1]&&this.b[0]==='r'&&!this.attacked(4,'w')&&!this.attacked(3,'w')&&!this.attacked(2,'w'))out.push(2)}return out}
  let dirs=k==='b'?[[1,1],[1,-1],[-1,1],[-1,-1]]:k==='r'?[[1,0],[-1,0],[0,1],[0,-1]]:[[1,1],[1,-1],[-1,1],[-1,-1],[1,0],[-1,0],[0,1],[0,-1]];for(let [dr,dc] of dirs){let rr=r+dr,cc=c+dc;while(this.at(rr,cc)>=0){let j=rr*8+cc;if(!this.b[j])out.push(j);else{if(this.color(this.b[j])!==this.color(p)||attacksOnly)out.push(j);break}rr+=dr;cc+=dc}}return out}
 attacked(i,by){for(let s=0;s<64;s++)if(this.b[s]&&this.color(this.b[s])===by&&this.pseudo(s,true).includes(i))return true;return false}
 inCheck(side){let k=this.b.findIndex(p=>p&&(p.toLowerCase()==='k')&&this.color(p)===side);return k>=0&&this.attacked(k,side==='w'?'b':'w')}
 legal(i){let p=this.b[i];return this.pseudo(i).filter(to=>{let old=this.b[to],from=this.b[i];this.b[to]=from;this.b[i]='';let safe=!this.inCheck(this.color(p));this.b[i]=from;this.b[to]=old;return safe})}
 allMoves(side){let a=[];for(let i=0;i<64;i++)if(this.b[i]&&this.color(this.b[i])===side)for(let to of this.legal(i))a.push([i,to]);return a}
 move(i){if(this.done)return;if(this.sel>=0&&this.moves.includes(i)){let p=this.b[this.sel],from=this.sel;this.b[i]=p;this.b[from]='';if(p==='P'&&i<8)this.b[i]='Q';if(p==='p'&&i>=56)this.b[i]='q';if(p==='K'){this.castle.K=this.castle.Q=false;if(i===62){this.b[61]='R';this.b[63]=''}if(i===58){this.b[59]='R';this.b[56]=''}}if(p==='k'){this.castle.k=this.castle.q=false;if(i===6){this.b[5]='r';this.b[7]=''}if(i===2){this.b[3]='r';this.b[0]=''}}if(from===63||i===63)this.castle.K=false;if(from===56||i===56)this.castle.Q=false;if(from===7||i===7)this.castle.k=false;if(from===0||i===0)this.castle.q=false;this.turn=this.turn==='w'?'b':'w';this.sel=-1;this.moves=[];let check=this.inCheck(this.turn),moves=this.allMoves(this.turn);if(!moves.length){this.done=check?(this.turn==='w'?'Jaque mate · ganan negras.':'Jaque mate · ganan blancas.'):'Tablas por ahogado.';this.msg=this.done}else this.msg=`Turno de ${this.turn==='w'?'blancas':'negras'}${check?' · ¡Jaque!':''}`;if(this.mode==='pve'&&this.turn==='b'&&!this.done)this.computer();return}if(this.b[i]&&this.color(this.b[i])===this.turn){this.sel=i;this.moves=this.legal(i)}}
 computer(){this.busy=true;const self=this;setTimeout(()=>{if(game!==self||self.done)return;let all=self.allMoves('b');if(all.length){let [from,to]=all[Math.random()*all.length|0];self.sel=from;self.moves=self.legal(from);self.busy=false;self.move(to)}else self.busy=false;render()},400)}
}
function renderChess(){let g=game,symbols={r:'♜',n:'♞',b:'♝',q:'♛',k:'♚',p:'♟',R:'♖',N:'♘',B:'♗',Q:'♕',K:'♔',P:'♙'},celebrate=localWinPending(),losingKing=g.done.includes('ganan blancas')?'k':'K';shell('Ajedrez',g.busy?'Turno de la computadora…':g.done||g.msg,`<div class="chess-board">${g.b.map((p,i)=>{let r=i/8|0,c=i%8;return `<button class="chess-cell ${(r+c)%2?'dark-square':'light-square'} ${r>=6?'white-piece-square':''} ${g.sel===i?'chosen':''} ${g.moves.includes(i)?'possible':''} ${celebrate&&p===losingKing?'mated-king':''}" data-i="${i}" aria-label="${!p?'Casilla vacía':symbols[p]+' '+String.fromCharCode(97+c)+(8-r)}" ${(g.busy||!localTurn()||g.mode==='pve'&&g.turn==='b')?'disabled':''}>${p?symbols[p]:''}</button>`}).join('')}</div><p class="board-hint">${g.mode==='pve'?'Tú juegas con blancas · computadora con negras':wifi.active?`Estás jugando como ${wifi.player===0?'blancas':'negras'}.`:'Dos jugadores · enroque y promoción a dama · sin captura al paso.'}</p>`);stage.querySelectorAll('.chess-cell').forEach(b=>b.onclick=()=>{if(!localTurn())return;g.move(+b.dataset.i);publishWifi();render()})}

init();
})();
