// Small dependency-free HTTP relay and static server for same-Wi-Fi matches.
const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto'),os=require('os');
const ROOT=__dirname,PORT=Number(process.env.SUDOMI_PORT||8787),rooms=new Map();
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.ico':'image/x-icon'};
function json(res,status,data){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(data))}
function roomCode(){let s='';const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';for(let i=0;i<6;i++)s+=chars[crypto.randomInt(chars.length)];return s}
function token(){return crypto.randomBytes(18).toString('hex')}
function target(room,player,event){const id=++room.seq,item={id,event};room.queues[player].push(item);const waiter=room.waiters[player];if(waiter){room.waiters[player]=null;pollReply(waiter,room,player,0)}}
function pollReply(res,room,player,since){if(res.writableEnded)return;const events=room.queues[player].filter(x=>x.id>since);if(events.length){const last=events[events.length-1].id;json(res,200,{events:events.map(x=>x.event),cursor:last});room.queues[player]=room.queues[player].filter(x=>x.id>last);return}room.waiters[player]=res;setTimeout(()=>{if(room.waiters[player]===res){room.waiters[player]=null;json(res,200,{events:[],cursor:since})}},20000)}
async function body(req){let s='';for await(const c of req)s+=c;return s?JSON.parse(s):{}}
function authorize(data){const room=rooms.get(String(data.room||'').toUpperCase()),p=Number(data.player);if(!room||!Number.isInteger(p)||p<0||p>1||room.tokens[p]!==data.token)throw Error('La sala no existe o la conexión expiró.');return {room,p}}
function api(req,res,url){if(url.pathname==='/api/create'&&req.method==='GET'){const game=url.searchParams.get('game');if(!['fleet','chess','checkers','tictactoe','connect4','domino','memory','dotsboxes','stop','mahjong','blackjack','poker','escoba','rummy'].includes(game))return json(res,400,{error:'Juego no disponible.'});let code;do{code=roomCode()}while(rooms.has(code));const r={code,game,tokens:[token(),null],queues:[[],[]],waiters:[null,null],seq:0,created:Date.now()};rooms.set(code,r);return json(res,200,{room:code,player:0,token:r.tokens[0],game})}
 if(url.pathname==='/api/join'&&req.method==='GET'){const code=(url.searchParams.get('room')||'').toUpperCase(),game=url.searchParams.get('game'),r=rooms.get(code);if(!r)return json(res,404,{error:'No encontramos esa sala. Revisa el código.'});if(r.game!==game)return json(res,400,{error:'La sala es para otro juego.'});if(r.tokens[1])return json(res,409,{error:'La sala ya tiene dos jugadores.'});r.tokens[1]=token();target(r,0,{type:'peer-joined'});return json(res,200,{room:code,player:1,token:r.tokens[1],game})}
 if(url.pathname==='/api/poll'&&req.method==='GET'){try{const {room,p}=authorize(Object.fromEntries(url.searchParams));pollReply(res,room,p,Number(url.searchParams.get('since')||0))}catch(e){json(res,401,{error:e.message})}return}
 if(url.pathname==='/api/send'&&req.method==='POST'){body(req).then(d=>{try{const {room,p}=authorize(d);if(!room.tokens[1-p])return json(res,409,{error:'El otro jugador todavía no se ha conectado.'});if(typeof d.type!=='string'||d.type.length>40)return json(res,400,{error:'Mensaje no válido.'});target(room,1-p,{type:d.type,payload:d.payload||{}});json(res,200,{ok:true})}catch(e){json(res,401,{error:e.message})}}).catch(()=>json(res,400,{error:'Solicitud no válida.'}));return}
 json(res,404,{error:'Ruta no encontrada.'})}
const server=http.createServer((req,res)=>{const url=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(url.pathname.startsWith('/api/'))return api(req,res,url);let pathname;try{pathname=decodeURIComponent(url.pathname)}catch{return json(res,400,{error:'Ruta no válida.'})}if(pathname==='/')pathname='/index.html';const file=path.resolve(ROOT,'.'+pathname);if(!file.startsWith(ROOT+path.sep)&&file!==path.join(ROOT,'index.html'))return json(res,403,{error:'Acceso denegado.'});fs.readFile(file,(e,data)=>{if(e){res.writeHead(404,{'Content-Type':'text/plain; charset=utf-8'});return res.end('Archivo no encontrado')}res.writeHead(200,{'Content-Type':mime[path.extname(file)]||'application/octet-stream','Cache-Control':'no-cache'});res.end(data)})});
server.listen(PORT,'0.0.0.0',()=>{console.log(`SUDOMI LAN activo en el puerto ${PORT}`);console.log('En esta PC: http://localhost:'+PORT);for(const list of Object.values(os.networkInterfaces()))for(const nic of list||[])if(nic.family==='IPv4'&&!nic.internal)console.log(`En tus teléfonos (misma Wi-Fi): http://${nic.address}:${PORT}`)});
setInterval(()=>{for(const [code,r] of rooms)if(Date.now()-r.created>6*60*60*1000){for(const w of r.waiters)if(w&&!w.writableEnded)json(w,410,{error:'La sala expiró.'});rooms.delete(code)}},30*60*1000).unref();
