export const SIZE=9;
const ROWS=[...Array(9).keys()];
const shuffled=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
export const idx=(r,c)=>r*9+c;
export const peers=i=>{const r=Math.floor(i/9),c=i%9,s=new Set();for(let x=0;x<9;x++){if(x!==c)s.add(idx(r,x));if(x!==r)s.add(idx(x,c))}const br=Math.floor(r/3)*3,bc=Math.floor(c/3)*3;for(let rr=br;rr<br+3;rr++)for(let cc=bc;cc<bc+3;cc++)if(rr!==r||cc!==c)s.add(idx(rr,cc));return [...s]};
export function candidates(board,i){if(board[i])return new Set();const used=new Set(peers(i).map(p=>board[p]).filter(Boolean));return new Set(ROWS.map(x=>x+1).filter(n=>!used.has(n)))}
function solveCount(board,limit=2){let best=-1,bestC=null;for(let i=0;i<81;i++)if(!board[i]){const c=candidates(board,i);if(c.size===0)return 0;if(!bestC||c.size<bestC.size){best=i;bestC=c;if(c.size===1)break}}if(best<0)return 1;let count=0;for(const n of shuffled([...bestC])){board[best]=n;count+=solveCount(board,limit);if(count>=limit){board[best]=0;return count}board[best]=0}return count}
export function countSolutions(board,limit=2){return solveCount([...board],limit)}
export function solve(board){const b=[...board];function rec(){let best=-1,bc=null;for(let i=0;i<81;i++)if(!b[i]){const c=candidates(b,i);if(!c.size)return false;if(!bc||c.size<bc.size){best=i;bc=c}}if(best<0)return true;for(const n of shuffled([...bc])){b[best]=n;if(rec())return true;b[best]=0}return false}return rec()?b:null}
export function generateSolution(){return solve(Array(81).fill(0))}
function carve(solution,targetClues){let puzzle=[...solution],order=shuffled(ROWS.map(r=>ROWS.flatMap(c=>[r*9+c])).flat());let clues=81;for(const i of order){if(clues<=targetClues)break;const old=puzzle[i];puzzle[i]=0;if(countSolutions(puzzle,2)!==1)puzzle[i]=old;else clues--}return puzzle}
export const DIFFICULTIES={
 easy:{label:'Fácil',clues:40,hintLimit:99},medium:{label:'Medio',clues:34,hintLimit:99},hard:{label:'Difícil',clues:30,hintLimit:1},expert:{label:'Experto',clues:27,hintLimit:1},master:{label:'Maestro',clues:25,hintLimit:1},extreme:{label:'Extremo',clues:23,hintLimit:1}
};
export function techniqueProfile(puzzle){let b=[...puzzle],steps=[];while(b.some(Boolean)===false?false:true){let progress=false;for(let i=0;i<81;i++)if(!b[i]){const c=candidates(b,i);if(c.size===1){b[i]=[...c][0];steps.push({type:'single',cell:i,value:b[i]});progress=true}}if(progress)continue;for(let unitType=0;unitType<3;unitType++){for(let u=0;u<9;u++){let cells=unitType===0?ROWS.map(c=>idx(u,c)):unitType===1?ROWS.map(r=>idx(r,u)):(()=>{const br=Math.floor(u/3)*3,bc=u%3*3;return [...Array(3)].flatMap((_,a)=>[...Array(3)].map((_,d)=>idx(br+a,bc+d)))})();for(let n=1;n<=9;n++){let poss=cells.filter(i=>!b[i]&&candidates(b,i).has(n));if(poss.length===1){b[poss[0]]=n;steps.push({type:'hidden-single',cell:poss[0],value:n});progress=true}}}}if(progress)continue;break}const unresolved=b.filter(x=>!x).length;return {steps,unresolved,level:unresolved?2:steps.some(s=>s.type==='hidden-single')?2:1};}
export function generatePuzzle(key='medium'){const d=DIFFICULTIES[key]||DIFFICULTIES.medium;let attempts=0;while(attempts++<20){const solution=generateSolution();const puzzle=carve(solution,d.clues);const profile=techniqueProfile(puzzle);if(key==='easy'&&profile.unresolved===0&&profile.level===1)return {puzzle,solution};if(key==='medium'&&profile.unresolved===0)return {puzzle,solution};if(['hard','expert','master','extreme'].includes(key))return {puzzle,solution}}const solution=generateSolution();return {puzzle:carve(solution,d.clues),solution};}
export function isComplete(board,solution){return board.every((n,i)=>n===solution[i])}
